import type { DepartmentDef } from "../types";

export const customer_experience: DepartmentDef = {
  id: "customer_experience",
  name: "Customer Experience",
  nameBn: "গ্রাহক অভিজ্ঞতা",
  icon: "🤝",
  description: "Customer support, feedback, premium service",
  primaryModel: "llama-3.3-70b",
  fallbackModels: ["hermes-3-405b", "nemotron-3-ultra"],
  teams: [
    {
      id: "customer_support",
      name: "Customer Support",
      nameBn: "গ্রাহক সাপোর্ট",
      department: "customer_experience",
      description: "First-line support, issue resolution, order tracking",
      primaryModel: "gpt-5.4-mini",
      fallbackModels: ["gemma-4-26b", "gemini-3.5-flash"],
      agents: [
        {
          id: "service_quality_manager", name: "Service Quality Manager", nameBn: "সেবা মান ব্যবস্থাপক",
          department: "customer_experience", team: "customer_support",
          description: "Monitors service quality across 5 SERVQUAL dimensions (Kotler Ch.9)",
          descriptionBn: "SERVQUAL-এর ৫ ডাইমেনশনে সেবা মান মনিটর করে (Kotler Ch.9)",
          expertise: "You monitor service quality using SERVQUAL: 1) Tangibility (UI/UX/appearance — our platform looks professional), 2) Reliability (delivery on time — consistent service), 3) Responsiveness (quick response — fast problem solving), 4) Assurance (trust/confidence — knowledgeable team), 5) Empathy (care/understanding — personalized attention). Check each dimension in every interaction. '৫টি ডাইমেনশনে এক্সেলেন্স নিশ্চিত করুন — প্রতিটি ইন্টারঅ্যাকশনে Tangibility থেকে Empathy পর্যন্ত।'",
          promptTemplate: "Monitor service quality: {{text}}, issue={{issue}}, mood={{mood}}. Check 5 SERVQUAL dimensions: Tangibility/Reliability/Responsiveness/Assurance/Empathy. Which dimension needs improvement? Specific action. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 85, when: "intent === 'complaint' || intent === 'support' || intent === 'feedback'",
        },
        {
          id: "faq_responder", name: "FAQ Responder", nameBn: "FAQ উত্তরদাতা",
          department: "customer_experience", team: "customer_support",
          description: "Answers common questions instantly from skill cache",
          descriptionBn: "সাধারণ প্রশ্নের স্কিল ক্যাশ থেকে তাৎক্ষণিক উত্তর দেয়",
          expertise: "You answer FAQs using Kotler's Product Levels (Ch.8): Core Benefit (what they truly need — skill/career/income), Actual Product (features — course content, videos, platform), Augmented Product (extra value — certificate, support, community, guarantee). Structure answers by product level. For pricing FAQ: show Core Value (income potential), Actual (what they get), Augmented (bonus support). 'FAQs কে Product Level অনুযায়ী উত্তর দিন — Core → Actual → Augmented — কাস্টমার পুরো ছবি দেখতে পায়।'",
          promptTemplate: "Answer FAQ using Product Levels: Core (what they truly need) → Actual (features/content) → Augmented (bonus/support). Question: {{question}}. Cover all 3 levels. Include links. End with 'আরো কিছু জানতে চান?' Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 100, when: "intent === 'general' || intent === 'product_inquiry' || intent === 'price_inquiry'",
        },
        {
          id: "order_status_checker", name: "Order Status Checker", nameBn: "অর্ডার স্ট্যাটাস চেকার",
          department: "customer_experience", team: "customer_support",
          description: "Checks and provides order status updates",
          descriptionBn: "অর্ডার স্ট্যাটাস চেক ও আপডেট দেয়",
          expertise: "You check order status: confirmed, processing, shipped, delivered. Provide ETA. Handle delays with transparency.",
          promptTemplate: "Check order {{orderId}}. Status: {{status}}, ETA: {{eta}}. If delayed → apologize + reason + new ETA. Language: {{language}}.",
          primaryModel: "hy3", fallbackModels: ["nemotron-nano"],
          tier: 4, priority: 90, when: "intent === 'general'",
        },
        {
          id: "payment_issue_resolver", name: "Payment Issue Resolver", nameBn: "পেমেন্ট সমস্যা সমাধানকারী",
          department: "customer_experience", team: "customer_support",
          description: "Resolves payment-related issues",
          descriptionBn: "পেমেন্ট সংক্রান্ত সমস্যা সমাধান করে",
          expertise: "You resolve payment issues: failed transaction, wrong charge, double charge, refund not received, payment not reflected.",
          promptTemplate: "Resolve payment issue: {{issue}}. Verify with gateway, check details, initiate correction. Keep customer updated. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 85, when: "intent === 'complaint' || intent === 'general'",
        },
        {
          id: "product_info_provider", name: "Product Info Provider", nameBn: "পণ্য তথ্য প্রদানকারী",
          department: "customer_experience", team: "customer_support",
          description: "Provides detailed product information",
          descriptionBn: "পণ্যের বিস্তারিত তথ্য দেয়",
          expertise: "You know all products: features, price, benefits, usage, availability, specifications, comparisons.",
          promptTemplate: "Provide product info for {{product}}. Features, price BDT, benefits, how to use, availability. Be detailed but clear. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 80, when: "intent === 'product_inquiry'",
        },
        {
          id: "delivery_tracker", name: "Delivery Tracker", nameBn: "ডেলিভারি ট্র্যাকার",
          department: "customer_experience", team: "customer_support",
          description: "Tracks product delivery status",
          descriptionBn: "পণ্য ডেলিভারি স্ট্যাটাস ট্র্যাক করে",
          expertise: "You track deliveries: courier, tracking number, location, ETA, delivery confirmation, delay handling.",
          promptTemplate: "Track delivery: courier={{courier}}, tracking={{tracking}}. Status: {{status}}, ETA={{eta}}. If delayed: apologize + new ETA. Language: {{language}}.",
          primaryModel: "hy3", fallbackModels: ["nemotron-nano"],
          tier: 4, priority: 75, when: "intent === 'general'",
        },
        {
          id: "return_exchange_handler", name: "Return/Exchange Handler", nameBn: "রিটার্ন/এক্সচেঞ্জ হ্যান্ডলার",
          department: "customer_experience", team: "customer_support",
          description: "Handles product returns and exchanges",
          descriptionBn: "পণ্য ফেরত ও বিনিময় পরিচালনা করে",
          expertise: "You handle returns: check policy, reason, condition, initiate return, arrange pickup, process refund/replacement.",
          promptTemplate: "Handle return: order={{orderId}}, reason={{reason}}. Check period, guide steps, inform timeline. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 70, when: "intent === 'complaint' || intent === 'general'",
        },
        {
          id: "refund_processor", name: "Refund Processor", nameBn: "রিফান্ড প্রসেসর",
          department: "customer_experience", team: "customer_support",
          description: "Processes refund requests",
          descriptionBn: "রিফান্ড রিকোয়েস্ট প্রসেস করে",
          expertise: "You process refunds: verify eligibility, calculate amount, initiate refund, notify customer, confirm completion.",
          promptTemplate: "Process refund: order={{orderId}}, amount={{amount}}, method={{method}}. Steps: verify → process → notify → confirm. Timeline: 5-7 days. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 80, when: "intent === 'complaint' || intent === 'general'",
        },
      ],
    },
    {
      id: "feedback_improvement",
      name: "Feedback & Improvement",
      nameBn: "ফিডব্যাক ও উন্নয়ন",
      department: "customer_experience",
      description: "Collect feedback and suggest improvements",
      primaryModel: "gpt-5.4-mini",
      fallbackModels: ["gemma-4-26b", "gemini-3.5-flash"],
      agents: [
        {
          id: "feedback_collector", name: "Feedback Collector", nameBn: "ফিডব্যাক সংগ্রহকারী",
          department: "customer_experience", team: "feedback_improvement",
          description: "Collects customer feedback after interactions",
          descriptionBn: "ইন্টারঅ্যাকশনের পর গ্রাহকের ফিডব্যাক সংগ্রহ করে",
          expertise: "You collect feedback using Kotler's Marketing Research (Ch.5): Questionnaire Design — Open-Ended ('আপনার মতামত কী?' — rich insights, harder to analyze) vs Closed-Ended (rating scales, multiple choice — easier to measure). Sampling: target right segment. Best practice: start open-ended (build rapport), end closed-ended (measure). 'ওপেন-এন্ডেড প্রশ্ন গভীর অন্তর্দৃষ্টি দেয়, ক্লোজড প্রশ্ন মাপার জন্য। দুটোই ব্যবহার করুন।' Timing: post-purchase, post-support, post-onboarding.",
          promptTemplate: "Collect feedback via Kotler Research methods. Open-ended: 'আপনার সবচেয়ে বড় চ্যালেঞ্জ কী?' Closed: '১-১০ স্কেলে রেট দিন?' Mix both. Segment-based timing. Friendly, short. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemini-3.5-flash"],
          tier: 3, priority: 90, when: "intent === 'purchase' || intent === 'registration'",
        },
        {
          id: "customer_satisfaction_tracker", name: "Customer Satisfaction Tracker", nameBn: "গ্রাহক সন্তুষ্টি ট্র্যাকার",
          department: "customer_experience", team: "feedback_improvement",
          description: "Tracks NPS, CSAT, CES scores and recommends improvements (Kotler Ch.5 + Ch.19)",
          descriptionBn: "NPS, CSAT, CES স্কোর ট্র্যাক করে এবং উন্নতি প্রস্তাব দেয় (Kotler Ch.5 + Ch.19)",
          expertise: "You track 3 key metrics: 1) NPS (Net Promoter Score 0-10 — Promoters 9-10 / Passives 7-8 / Detractors 0-6), 2) CSAT (Customer Satisfaction 1-5), 3) CES (Customer Effort Score 1-5 — lower is better). Collect after each interaction. Analyze trends. NPS = %Promoters − %Detractors. 'Detractors are a goldmine — ask them 'কী কারণে আপনি ৬ দিলেন?' এবং উন্নতি করুন।'",
          promptTemplate: "Track satisfaction: {{text}}, customer={{name}}, interaction={{interaction}}. Assess NPS/CSAT/CES, recommend improvement. Collect follow-up if needed. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemini-3.5-flash"],
          tier: 3, priority: 80, when: "intent === 'feedback' || intent === 'purchase' || intent === 'support'",
        },
        {
          id: "improvement_suggester", name: "Improvement Suggester", nameBn: "উন্নতি প্রস্তাবকারী",
          department: "customer_experience", team: "feedback_improvement",
          description: "Suggests process improvements from feedback",
          descriptionBn: "ফিডব্যাক থেকে প্রক্রিয়া উন্নতির প্রস্তাব দেয়",
          expertise: "You generate marketing insights using Kotler's Marketing Research (Ch.5) — Big Data Analytics + Marketing Planning (Ch.2). Analyze feedback patterns: segmentation (which segment complains about what?), trend analysis (increasing/decreasing issues), correlation (does price feedback correlate with segment?). Turn insights into Marketing Plan actions: Product changes, Pricing adjustments, Promotion focus, Place (distribution) improvements. 'ডেটা থেকে ইনসাইট → ইনসাইট থেকে অ্যাকশন → অ্যাকশন থেকে ইম্প্রুভমেন্ট। প্রতিটি ফিডব্যাক একটি মার্কেটিং সুযোগ।'",
          promptTemplate: "Generate marketing insights from feedback: {{pattern}}. Apply Big Data Analysis: segment patterns, trends, correlations. Feed into Marketing Plan: product/pricing/promotion/place recommendations. Top 3 actionable suggestions with impact. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 75, when: "intent === 'feedback'",
        },
      ],
    },
    {
      id: "premium_experience",
      name: "Premium Experience",
      nameBn: "প্রিমিয়াম অভিজ্ঞতা",
      department: "customer_experience",
      description: "Personalized greetings, tone adjustment, cultural respect",
      primaryModel: "llama-3.3-70b",
      fallbackModels: ["hermes-3-405b", "nemotron-3-ultra"],
      agents: [
        {
          id: "greeting_personalizer", name: "Greeting Personalizer", nameBn: "গ্রিটিং পার্সোনালাইজার",
          department: "customer_experience", team: "premium_experience",
          description: "Greets based on name, religion, language",
          descriptionBn: "নাম, ধর্ম, ভাষা অনুসারে গ্রিটিং দেয়",
          expertise: "You personalize greetings using Kotler's Cultural Factors (Ch.3): Culture (national identity — Bangladeshi values of respect, hospitality), Subculture (regional/religious — Muslim/Hindu, urban/rural), Social Class (education, occupation). Adapt greeting + tone per cultural context. 'সংস্কৃতি অনুযায়ী গ্রিটিং = তাৎক্ষণিক কানেকশন। Bangladesh-এ 'Assalamu Alaikum' শুধু ধর্মীয় না — এটা সাংস্কৃতিক সম্মান।' Respect hierarchy (বয়স, স্ট্যাটাস) and use appropriate formality level.",
          promptTemplate: "Personalize greeting via Cultural Factors. Name={{name}}, religion={{religion}}, language={{language}}, region={{region}}, ageGroup={{age}}. Use culturally appropriate greeting. Respect hierarchy, subculture norms. Warm, respectful. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 95, when: "intent === 'greeting'",
        },
        {
          id: "tone_adjuster", name: "Tone Adjuster", nameBn: "টোন এডজাস্টার",
          department: "customer_experience", team: "premium_experience",
          description: "Adjusts response tone based on customer mood",
          descriptionBn: "গ্রাহকের মুড অনুসারে টোন এডজাস্ট করে",
          expertise: "You adjust tone using Kotler's IMC Communication Adaptation (Ch.12): Push Strategy (direct message — for analytical/logical customers who want info) vs Pull Strategy (attract through content/value — for customers who need inspiration). Adapt per communication channel and customer preference. 'Push = সরাসরি তথ্য দিয়ে রাজি করান। Pull = মূল্য দিয়ে আকর্ষণ করুন। প্রতিটি কাস্টমারের জন্য সঠিক স্ট্র্যাটেজি নির্বাচন করুন।' Also adapt tone to mood: angry→calm, happy→energetic, sad→gentle, neutral→friendly.",
          promptTemplate: "Adjust tone via Push vs Pull strategy. Customer preference: analytical/emotional. Push (direct info/data) or Pull (value/inspiration). Also adapt to mood={{mood}}: angry→calm, happy→energetic, sad→gentle, neutral→friendly. Mirror energy. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 90, when: "intent === 'complaint' || intent === 'general'",
        },
        {
          id: "culture_respector", name: "Culture Respector", nameBn: "সংস্কৃতি সম্মানকারী",
          department: "customer_experience", team: "premium_experience",
          description: "Respects cultural norms and sensitivities",
          descriptionBn: "সাংস্কৃতিক নিয়ম ও সংবেদনশীলতা সম্মান করে",
          expertise: "You respect cultural norms: appropriate greetings by religion, modesty, family values, festival greetings (Eid/Puja), time sensitivity.",
          promptTemplate: "Apply cultural respect. Religion={{religion}}, occasion={{occasion}}. Use appropriate greeting, avoid sensitive topics, respect norms. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 85, when: "intent === 'greeting'",
        },
        {
          id: "premium_badge_notifier", name: "Premium Badge Notifier", nameBn: "প্রিমিয়াম ব্যাজ নোটিফায়ার",
          department: "customer_experience", team: "premium_experience",
          description: "Welcomes premium members with Golden Rule — family, not transaction",
          descriptionBn: "প্রিমিয়াম সদস্যদের স্বাগত জানায় — 'আপনি আমাদের পরিবারের বিশেষ সদস্য'",
          expertise: "You apply Golden Rule of Influence: Premium Members are family, not numbers. Know their name, journey, history. For Premium: 'আপনি আমাদের পরিবারের বিশেষ সদস্য — আপনার সাফল্যই আমাদের সাফল্য.' For General: Show value first — demonstrate how Premium changes their life. Never push upgrade. Guide them.",
          promptTemplate: "Member tier={{memberTier}}, name={{name}}, history={{history}}. If Premium: Golden Rule — 'You're a special member of our family.' Reference their name, their journey. Mention benefits as tools for their growth: 'Zero withdrawal tax means more income for your family.' If General: show value first. 'Others in your situation found Premium helpful because...' Let them feel the decision is theirs. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 65, when: "intent === 'registration' || intent === 'purchase'",
        },
        {
          id: "loyalty_program_manager", name: "Loyalty Program Manager", nameBn: "আনুগত্য প্রোগ্রাম ব্যবস্থাপক",
          department: "customer_experience", team: "premium_experience",
          description: "Manages loyalty programs and retention strategies (Kotler Ch.19)",
          descriptionBn: "আনুগত্য প্রোগ্রাম ও রিটেনশন কৌশল পরিচালনা করে (Kotler Ch.19)",
          expertise: "You recommend loyalty programs: 1) Points-based (earn points per purchase → redeem), 2) Tiered (Silver/Gold/Platinum — increasing benefits), 3) Value-Add (exclusive content/early access), 4) Coalition (partner discounts), 5) Paid (Amazon Prime style). Calculate CLV impact. Recommend retention strategies: personalization, surprise rewards, membership benefits. 'আমাদের লয়ালটি প্রোগ্রাম শুধু ডিসকাউন্ট নয় — এটি সম্পর্ক গড়ার একটি টুল।'",
          promptTemplate: "Manage loyalty. Customer={{name}}, stage={{loyaltyStage}}, history={{history}}. Recommend loyalty program type: points/tiered/value-add/coalition/paid. Suggest retention strategy. Consider CLV impact. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 75, when: "intent === 'purchase' || intent === 'general' || intent === 'feedback'",
        },
        {
          id: "premium_dedicated_support", name: "Premium Dedicated Support", nameBn: "প্রিমিয়াম ডেডিকেটেড সাপোর্ট",
          department: "customer_experience", team: "premium_experience",
          description: "Knows premium member's name, preferences, history for personalized care",
          descriptionBn: "প্রিমিয়াম সদস্যের নাম, পছন্দ ও ইতিহাস জানে — ব্যক্তিগতকৃত সেবা দেয়",
          expertise: "You are a dedicated support agent for Premium Members. You know their name, purchase history, preferences, past conversations. Use Law of Influence: 'We together are growing your business.' Always reference past interactions. 'Last time we discussed X — how did that go?' Make them feel known, seen, and valued as individuals.",
          promptTemplate: "Premium member: name={{name}}, history={{history}}, preferences={{preferences}}, lastInteraction={{lastInteraction}}. Reference past conversations. Ask about their progress. Use 'We' framing: 'We've come so far together.' Offer personalized support. Never generic — always specific to their journey. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 2, priority: 70, when: "isPremium === true",
        },
      ],
    },
  ],
};
