import type { DepartmentDef } from "../types";

export const operations: DepartmentDef = {
  id: "operations",
  name: "Operations",
  nameBn: "অপারেশনস",
  icon: "⚙️",
  description: "Order processing, payments, withdrawals",
  primaryModel: "llama-3.3-70b",
  fallbackModels: ["nemotron-3-ultra", "hermes-3-405b"],
  teams: [
    {
      id: "order_management",
      name: "Order Management",
      nameBn: "অর্ডার ম্যানেজমেন্ট",
      department: "operations",
      description: "Process, track, and manage orders",
      primaryModel: "gpt-5.4-mini",
      fallbackModels: ["gemma-4-26b", "gemini-3.5-flash"],
      agents: [
        {
          id: "order_creator", name: "Order Creator", nameBn: "অর্ডার ক্রিয়েটর",
          department: "operations", team: "order_management",
          description: "Creates and validates new orders",
          descriptionBn: "নতুন অর্ডার তৈরি ও ভ্যালিডেট করে",
          expertise: "You create orders using Kotler's Integrated Logistics Management (Ch.15): 4 stages — 1) Order Processing (receive, verify, enter), 2) Inventory (check stock, allocate), 3) Warehousing (pick, pack), 4) Transportation (ship, deliver). 'অর্ডার ফুলফিলমেন্ট শুধু অর্ডার নেওয়া নয় — লজিস্টিকসের ৪টি স্টেজের সমন্বয়। প্রতিটি স্টেজ সঠিকভাবে সম্পন্ন হলে কাস্টমার সন্তুষ্টি নিশ্চিত।' Coordinate all stages smoothly.",
          promptTemplate: "Create order using 4-stage logistics: 1) Order Processing (verify customer={{name}}, product={{product}}, qty={{qty}}), 2) Inventory (stock check), 3) Warehouse (allocate), 4) Transport (schedule). Return order ID. Coordinate all stages. Language: {{language}}.",
          primaryModel: "hy3", fallbackModels: ["nemotron-nano"],
          tier: 4, priority: 95, when: "intent === 'purchase'",
        },
        {
          id: "order_verifier", name: "Order Verifier", nameBn: "অর্ডার ভেরিফায়ার",
          department: "operations", team: "order_management",
          description: "Confirms orders after payment verification",
          descriptionBn: "পেমেন্ট কনফার্ম হলে অর্ডার কনফার্ম করে",
          expertise: "You verify orders: check payment confirmation, match amount, update order status, trigger fulfillment.",
          promptTemplate: "Verify order {{orderId}}. Payment={{paymentStatus}}, amount={{amount}}. If confirmed → update status to confirmed, notify customer. Language: {{language}}.",
          primaryModel: "hy3", fallbackModels: ["nemotron-nano"],
          tier: 4, priority: 90, when: "intent === 'purchase'",
        },
        {
          id: "invoice_generator", name: "Invoice Generator", nameBn: "ইনভয়েস জেনারেটর",
          department: "operations", team: "order_management",
          description: "Generates invoices for orders",
          descriptionBn: "অর্ডারের জন্য ইনভয়েস তৈরি করে",
          expertise: "You generate invoices: order details, pricing, taxes, total, payment terms, company info, customer info.",
          promptTemplate: "Generate invoice. Order={{orderId}}, items={{items}}, total={{total}}, tax={{tax}}, payment={{method}}. Professional format. Language: {{language}}.",
          primaryModel: "hy3", fallbackModels: ["nemotron-nano"],
          tier: 4, priority: 80, when: "intent === 'purchase'",
        },
        {
          id: "distribution_optimizer", name: "Distribution Optimizer", nameBn: "ডিস্ট্রিবিউশন অপটিমাইজার",
          department: "operations", team: "order_management",
          description: "Optimizes distribution channels using Kotler's Channel Levels + VMS (Ch.15)",
          descriptionBn: "Kotler-র Channel Levels + VMS ব্যবহার করে ডিস্ট্রিবিউশন চ্যানেল অপটিমাইজ করে (Ch.15)",
          expertise: "You optimize distribution: Channel Levels — Level 0 (Direct: WhatsApp/Call — highest margin), Level 1 (Retailer — one intermediary), Level 2 (Wholesaler → Retailer), Level 3 (Full chain). VMS types: Corporate (own), Contractual (franchise/partnership), Administered (leading brand-driven). Push vs Pull: Push (incentivize partners) vs Pull (create customer demand). Channel Conflict Resolution: goal conflict, role ambiguity, perceptual differences. 'সঠিক চ্যানেল = সঠিক কভারেজ + সঠিক মার্জিন। ব্যালেন্স গুরুত্বপূর্ণ।'",
          promptTemplate: "Optimize distribution. Product={{product}}, target={{segment}}, currentChannel={{channel}}. Recommend: channel level (0/1/2/3), VMS type, push vs pull strategy. Consider Bangladeshi distribution context. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 72, when: "intent === 'general' || intent === 'product_inquiry'",
        },
        {
          id: "retail_partner_manager", name: "Retail Partner Manager", nameBn: "রিটেইল পার্টনার ম্যানেজার",
          department: "operations", team: "order_management",
          description: "Manages retail partnerships using Retail Mix + Omni-Channel (Kotler Ch.16)",
          descriptionBn: "Retail Mix + Omni-Channel ব্যবহার করে রিটেইল পার্টনারশিপ ম্যানেজ করে (Kotler Ch.16)",
          expertise: "You manage retail partnerships: Retail Mix (6 Ps) — Product, Price, Place, Promotion, Presentation (Visual Merchandising), Personnel. Store Atmosphere (SOR Model: Stimulus → Organism → Response). Omni-Channel: seamless customer experience across Facebook + Website + WhatsApp + Physical location. Category Management: organize products/courses into logical categories. Bangladesh context: 'Facebook + WhatsApp + Physical Spot = বাংলাদেশের জন্য পারফেক্ট Omni-Channel স্ট্র্যাটেজি।'",
          promptTemplate: "Manage retail partner. Partner={{partner}}, context={{text}}. Retail Mix recommendation: product/price/place/promotion/presentation/personnel. Omni-Channel consistency. Store atmosphere tips for Bangladeshi context. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 68, when: "intent === 'general' || intent === 'product_inquiry'",
        },
        {
          id: "inventory_updater", name: "Inventory Updater", nameBn: "ইনভেন্টরি আপডেটার",
          department: "operations", team: "order_management",
          description: "Updates stock levels when orders are placed",
          descriptionBn: "অর্ডার প্লেস হলে স্টক লেভেল আপডেট করে",
          expertise: "You update inventory: deduct ordered items, trigger low stock alerts, update availability status, sync with product pages.",
          promptTemplate: "Update inventory. Product={{product}}, ordered={{qty}}, current={{stock}}, new={{newStock}}. If low stock: alert. Update status. Language: {{language}}.",
          primaryModel: "hy3", fallbackModels: ["nemotron-nano"],
          tier: 4, priority: 75, when: "intent === 'purchase'",
        },
        {
          id: "order_notifier", name: "Order Notifier", nameBn: "অর্ডার নোটিফায়ার",
          department: "operations", team: "order_management",
          description: "Sends order updates to customers",
          descriptionBn: "গ্রাহককে অর্ডার আপডেট পাঠায়",
          expertise: "You notify customers: order confirmed, processing, shipped, out for delivery, delivered, delayed.",
          promptTemplate: "Send order update. Order={{orderId}}, status={{status}}, details={{details}}. Keep customer informed and excited. Language: {{language}}.",
          primaryModel: "hy3", fallbackModels: ["nemotron-nano"],
          tier: 4, priority: 85, when: "intent === 'purchase'",
        },
      ],
    },
    {
      id: "payment_processing",
      name: "Payment Processing",
      nameBn: "পেমেন্ট প্রসেসিং",
      department: "operations",
      description: "Process, verify, and track payments",
      primaryModel: "gpt-5.4-mini",
      fallbackModels: ["gemma-4-26b", "gemini-3.5-flash"],
      agents: [
        {
          id: "sslcommerz_initiator", name: "SSLCommerz Initiator", nameBn: "SSLCommerz ইনিশিয়েটর",
          department: "operations", team: "payment_processing",
          description: "Initiates SSLCommerz payment gateway",
          descriptionBn: "SSLCommerz পেমেন্ট গেটওয়ে ইনিশিয়েট করে",
          expertise: "You initiate SSLCommerz payments: generate payment URL, pass order details, handle success/cancel/fail URLs.",
          promptTemplate: "Initiate SSLCommerz payment. Order={{orderId}}, amount={{amount}} BDT. Generate payment link. Instruct customer. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 95, when: "intent === 'purchase'",
        },
        {
          id: "ipn_validator", name: "IPN Validator", nameBn: "IPN ভ্যালিডেটর",
          department: "operations", team: "payment_processing",
          description: "Validates IPN (Instant Payment Notification)",
          descriptionBn: "IPN ভ্যালিডেশন ও ভারিফিকেশন করে",
          expertise: "You validate IPN: verify signature, check amount matches, confirm transaction ID, update order status.",
          promptTemplate: "Validate IPN: trxID={{trxId}}, amount={{amount}}, status={{status}}. Verify signature, match order, update. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 90, when: "intent === 'purchase'",
        },
        {
          id: "payment_status_checker", name: "Payment Status Checker", nameBn: "পেমেন্ট স্ট্যাটাস চেকার",
          department: "operations", team: "payment_processing",
          description: "Checks payment status for orders",
          descriptionBn: "অর্ডারের পেমেন্ট স্ট্যাটাস চেক করে",
          expertise: "You check payment status with Kotler's Pricing Psychology (Ch.11): Transaction Cost (payment fees — educate customer on gateway charges), Installment Effect (installments reduce perceived price — 'মাসে মাত্র X টাকা দাম মনে হয় কম'), Price-Quality Inference (smooth payment process = professional brand). Apply pricing psychology in payment communication: frame fees as investment, highlight installment benefits, reassure with secure gateway. 'পেমেন্ট অভিজ্ঞতাও প্রাইসিং সাইকোলজির অংশ — মসৃণ লেনদেন ব্র্যান্ডের প্রতি আস্থা বাড়ায়।'",
          promptTemplate: "Check payment: order={{orderId}}, status=pending/processing/completed/failed/refunded. Apply pricing psychology: transaction cost explain, installment benefit, price-quality assurance. Guide next step with positive framing. Language: {{language}}.",
          primaryModel: "hy3", fallbackModels: ["nemotron-nano"],
          tier: 4, priority: 80, when: "intent === 'general' || intent === 'complaint'",
        },
        {
          id: "refund_initiator", name: "Refund Initiator", nameBn: "রিফান্ড ইনিশিয়েটর",
          department: "operations", team: "payment_processing",
          description: "Initiates payment refunds",
          descriptionBn: "পেমেন্ট রিফান্ড ইনিশিয়েট করে",
          expertise: "You initiate refunds: verify eligibility, process through gateway, notify customer, track refund status.",
          promptTemplate: "Initiate refund: order={{orderId}}, amount={{amount}}, reason={{reason}}. Process via gateway, notify customer, provide reference. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 85, when: "intent === 'complaint'",
        },
        {
          id: "transaction_logger", name: "Transaction Logger", nameBn: "ট্রানজেকশন লগার",
          department: "operations", team: "payment_processing",
          description: "Logs all financial transactions",
          descriptionBn: "সব আর্থিক লেনদেন লগ করে",
          expertise: "You log transactions: order payments, commissions, withdrawals, bonuses, refunds. Date, amount, type, reference.",
          promptTemplate: "Log transaction: type={{type}}, amount={{amount}}, reference={{ref}}, customer={{customer}}. Record with timestamp. Language: {{language}}.",
          primaryModel: "hy3", fallbackModels: ["nemotron-nano"],
          tier: 4, priority: 70, when: "intent === 'purchase' || intent === 'withdrawal'",
        },
        {
          id: "fraud_detector", name: "Fraud Detector", nameBn: "ফ্রড ডিটেক্টর",
          department: "operations", team: "payment_processing",
          description: "Detects suspicious payment activities",
          descriptionBn: "সন্দেহজনক পেমেন্ট অ্যাক্টিভিটি ডিটেক্ট করে",
          expertise: "You detect fraud through Kotler's Ethical Marketing & Consumer Privacy (Ch.21): protect customer data, respect privacy, ensure transparency. 'গ্রাহক ডেটা সুরক্ষা আমাদের দায়িত্ব — আমরা যেভাবে তথ্য সংগ্রহ করি, ব্যবহার করি এবং রক্ষা করি তাতে সম্পূর্ণ স্বচ্ছ।' Detect: unusual patterns, mismatched details, rapid transactions. Apply ethical checks: is this transaction transparent? Is customer data protected? Is our marketing ethical? Ethical = Trust = Long-term Value.",
          promptTemplate: "Detect fraud with Ethical Marketing check. Transaction={{trx}}, pattern={{pattern}}. Risk: high/medium/low. Apply consumer privacy check: data protection, transparency. 'আমরা আপনার তথ্য সুরক্ষিত রাখি — প্রতিটি লেনদেন স্বচ্ছ।' If high risk → block + notify admin. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["deepseek-v4-flash-free"],
          tier: 2, priority: 95, when: "intent === 'purchase'",
        },
      ],
    },
    {
      id: "withdrawal_management",
      name: "Withdrawal Management",
      nameBn: "উইথড্রয়াল ম্যানেজমেন্ট",
      department: "operations",
      description: "Process and manage commission withdrawals",
      primaryModel: "gpt-5.4-mini",
      fallbackModels: ["gemma-4-26b", "gemini-3.5-flash"],
      agents: [
        {
          id: "withdrawal_validator", name: "Withdrawal Validator", nameBn: "উইথড্রয়াল ভ্যালিডেটর",
          department: "operations", team: "withdrawal_management",
          description: "Validates withdrawal requests",
          descriptionBn: "উইথড্রয়াল রিকোয়েস্ট চেক করে",
          expertise: "You validate withdrawals: check minimum balance, verify identity, confirm method, check frequency limits.",
          promptTemplate: "Validate withdrawal: balance={{balance}}, requested={{amount}}, min={{min}}, method={{method}}. Valid yes/no. Reason if invalid. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 95, when: "intent === 'withdrawal'",
        },
        {
          id: "withdrawal_approver", name: "Withdrawal Approver", nameBn: "উইথড্রয়াল অ্যাপ্রুভার",
          department: "operations", team: "withdrawal_management",
          description: "Auto-approves small, flags large withdrawals",
          descriptionBn: "ছোট অঙ্ক অটো-অ্যাপ্রুভ, বড় অঙ্ক ফ্ল্যাগ করে",
          expertise: "You approve withdrawals: small amounts (under threshold) → auto, large amounts → manual review, suspicious → hold.",
          promptTemplate: "Approve withdrawal: amount={{amount}}, threshold={{threshold}}. If under → auto-approve. If over → flag for manual review. If suspicious → hold. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 90, when: "intent === 'withdrawal'",
        },
        {
          id: "payment_sender", name: "Payment Sender", nameBn: "পেমেন্ট প্রেরক",
          department: "operations", team: "withdrawal_management",
          description: "Sends payments via bKash/Nagad/bank",
          descriptionBn: "bKash/Nagad/ব্যাংকে পেমেন্ট পাঠায়",
          expertise: "You send payments: process via selected method, confirm receipt, provide reference, update member.",
          promptTemplate: "Send payment: member={{name}}, amount={{amount}}, method={{method}}, account={{account}}. Process, confirm, notify with reference. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 85, when: "intent === 'withdrawal'",
        },
        {
          id: "withdrawal_notifier", name: "Withdrawal Notifier", nameBn: "উইথড্রয়াল নোটিফায়ার",
          department: "operations", team: "withdrawal_management",
          description: "Notifies members about withdrawal status",
          descriptionBn: "উইথড্রয়াল স্ট্যাটাস সম্পর্কে কর্মীকে জানায়",
          expertise: "You notify: request received, processing, approved, sent, completed, or rejected with reason.",
          promptTemplate: "Notify withdrawal status: status={{status}}, amount={{amount}}, method={{method}}. Clear update with next steps. Language: {{language}}.",
          primaryModel: "hy3", fallbackModels: ["nemotron-nano"],
          tier: 4, priority: 75, when: "intent === 'withdrawal'",
        },
      ],
    },
  ],
};
