export interface SeedEntry {
  category: string;
  title: string;
  content: string;
  sourceType: string;
  sourceName: string;
  tags: string[];
  confidence: number;
}

export const ALL_ENTRIES: SeedEntry[] = [
  // ═══════════════════════════════════════════════════
  // BOOK: Talking with Psychopaths — Christopher Berry-Dee
  // ═══════════════════════════════════════════════════
  { category:"psychology", title:"Vulnerability Mirroring", content:"Reflect unspoken fears gently. When customer shows hesitation or doubt, validate their caution and frame it as wisdom. 'I sense you've been hurt before. That's why you're cautious — and that's wise.' This builds trust by acknowledging their reality without judgment.", sourceType:"book", sourceName:"Talking with Psychopaths and Savages", tags:["berry-dee","psychology","trust"], confidence:0.9 },
  { category:"psychology", title:"Trust Calibration", content:"Measure trust by the type of questions asked. 'How' questions = building trust. 'Why' questions = still skeptical. Adapt pacing accordingly. Never push when trust is low — provide proof and transparency instead.", sourceType:"book", sourceName:"Talking with Psychopaths and Savages", tags:["berry-dee","psychology","trust"], confidence:0.9 },
  { category:"safety", title:"Autonomy Preservation", content:"Never make customers feel controlled. Psychopaths control; ethical agents empower. Use phrases like 'you decide', 'your choice', 'only if it feels right'. Give complete autonomy in decision-making.", sourceType:"book", sourceName:"Talking with Psychopaths and Savages", tags:["berry-dee","safety","ethics"], confidence:0.9 },
  { category:"psychology", title:"Fear Transformation", content:"Transform fear of loss into desire for gain. When customer fears losing money, reframe: 'You're not risking anything — you're investing in a future where you wake up without that worry.' Turn negative fear into positive motivation.", sourceType:"book", sourceName:"Talking with Psychopaths and Savages", tags:["berry-dee","psychology","sales"], confidence:0.85 },
  { category:"psychology", title:"Mask Lowering Protocol", content:"When customers give perfect answers ('everything is fine', 'no problem'), they may be wearing a mask. Create safe space: 'It's ok to not be ok. What's really going on?' Gentle permission to be vulnerable builds deeper trust.", sourceType:"book", sourceName:"Talking with Psychopaths and Savages", tags:["berry-dee","psychology","communication"], confidence:0.85 },
  { category:"communication", title:"Pattern Interrupt", content:"When customer is stuck in a negative loop (scam fear, doubt, hesitation), interrupt with an unexpected question that shifts perspective: 'If money weren't a factor, what would your ideal life look like?' Breaks the negative pattern.", sourceType:"book", sourceName:"Talking with Psychopaths and Savages", tags:["berry-dee","communication","sales"], confidence:0.85 },
  { category:"communication", title:"Deep Listening", content:"Listen to what is NOT said. Pauses, hesitations, vague answers reveal more than words. Acknowledge silence: 'I can see you're thinking deeply about this.' This validates their thought process and deepens rapport.", sourceType:"book", sourceName:"Talking with Psychopaths and Savages", tags:["berry-dee","communication","psychology"], confidence:0.9 },
  { category:"sales", title:"Identity Affirmation", content:"Connect the offer to who they ARE, not who they could be. 'You're someone who values security for your family. This aligns with that.' Identity-based persuasion is more powerful than aspiration-based.", sourceType:"book", sourceName:"Talking with Psychopaths and Savages", tags:["berry-dee","sales","psychology"], confidence:0.85 },
  { category:"safety", title:"Doctor Shipman Warning — Never Exploit Trust", content:"Never exploit trust for gain. The most dangerous predators weaponize the trust others place in them. Always be worthy of the trust customers give you. Transparency and honesty are non-negotiable.", sourceType:"book", sourceName:"Talking with Psychopaths and Savages", tags:["berry-dee","safety","ethics"], confidence:1.0 },
  { category:"safety", title:"The Mask of Normality", content:"Most dangerous people appear perfectly normal, charming, and trustworthy. Teach agents to look beyond surface charm to detect genuine vs. performed emotions. Sincere care vs. calculated charm: the difference is consistency over time.", sourceType:"book", sourceName:"Talking with Psychopaths and Savages", tags:["berry-dee","safety","psychology"], confidence:0.9 },

  // ═══════════════════════════════════════════════════
  // BOOK: The Art of Persuasion — Bob Berg
  // ═══════════════════════════════════════════════════
  { category:"trust", title:"Golden Rule of Influence", content:"People do business with those they know, like, and trust. Trust is your strongest currency. Before any ask, invest in trust first. Every interaction is a chance to build trust currency.", sourceType:"book", sourceName:"The Art of Persuasion by Bob Berg", tags:["bob-berg","trust","sales"], confidence:0.95 },
  { category:"psychology", title:"Persuader's Mindset — Give First", content:"Influence = Service. Shift from 'what can I get' to 'what can I give'. Give free value — tips, insights, encouragement — before asking for anything. People are drawn to those who give without expectation.", sourceType:"book", sourceName:"The Art of Persuasion by Bob Berg", tags:["bob-berg","psychology","sales"], confidence:0.95 },
  { category:"communication", title:"Active Listening — 3 Techniques", content:"1) Reference their previous messages to show you remember, 2) Let them finish completely before responding, 3) Recap their words: 'So you're saying that...'. Silence is powerful. Let them fill the pause.", sourceType:"book", sourceName:"The Art of Persuasion by Bob Berg", tags:["bob-berg","communication"], confidence:0.9 },
  { category:"communication", title:"Speak Their Language — Framing", content:"Frame everything from their perspective, not yours. Match their communication style: analytical (data), emotional (feelings), direct (action), warm (relationship). 'This is best' -> 'This will make your life easier.'", sourceType:"book", sourceName:"The Art of Persuasion by Bob Berg", tags:["bob-berg","communication","sales"], confidence:0.9 },
  { category:"sales", title:"Law of Value", content:"Your worth = how much value you add to their life. People don't buy products, they buy better versions of themselves. Show the transformation, not just the features.", sourceType:"book", sourceName:"The Art of Persuasion by Bob Berg", tags:["bob-berg","sales"], confidence:0.9 },
  { category:"psychology", title:"Law of Influence — You Before Me", content:"Focus on 'you', 'we', 'us' — never 'me' or 'I'. The more you help others grow, the more your influence grows. Influence is what people feel when you're done speaking.", sourceType:"book", sourceName:"The Art of Persuasion by Bob Berg", tags:["bob-berg","psychology","communication"], confidence:0.9 },
  { category:"sales", title:"Handling Resistance — We're Together", content:"Don't fight resistance, understand it. Turn 'me vs you' into 'we're on the same team'. 'You're right to be careful — let's find the best solution together.' Resistance drops when they feel you're on their side.", sourceType:"book", sourceName:"The Art of Persuasion by Bob Berg", tags:["bob-berg","sales","psychology"], confidence:0.9 },
  { category:"communication", title:"Power of Subtlety — Guide Not Pusher", content:"Be the guide, not the pusher. Instead of 'You should buy this', say 'Others in your situation found this helpful.' Let them feel the decision is theirs. No push, no pressure.", sourceType:"book", sourceName:"The Art of Persuasion by Bob Berg", tags:["bob-berg","communication","sales"], confidence:0.9 },
  { category:"psychology", title:"Influence as a Daily Habit", content:"Influence is not a one-time tactic, it's a daily habit. 1) Who can I help today? 2) Listen before answering. 3) Speak their language. 4) Create an environment where people feel heard and inspired.", sourceType:"book", sourceName:"The Art of Persuasion by Bob Berg", tags:["bob-berg","psychology","trust"], confidence:0.85 },
  { category:"trust", title:"Trust is Your Strongest Currency", content:"Money can be earned and lost, but trust once gained is the most valuable asset. Every honest word, every good deed, every empathetic interaction grows this currency without interest.", sourceType:"book", sourceName:"The Art of Persuasion by Bob Berg", tags:["bob-berg","trust","ethics"], confidence:0.95 },

  // ═══════════════════════════════════════════════════
  // BOOK: Blue Ocean Strategy — Kim & Mauborgne
  // ═══════════════════════════════════════════════════
  { category:"strategy", title:"Core Principle — Value Innovation", content:"Value Innovation = pursue differentiation AND low cost simultaneously. Don't compete on price OR quality. Find the unique combination that creates leap in value. Ask: what can we eliminate, reduce, raise, create?", sourceType:"book", sourceName:"Blue Ocean Strategy", tags:["blue-ocean","strategy","sales"], confidence:0.9 },
  { category:"strategy", title:"ERRC Grid — Eliminate-Reduce-Raise-Create", content:"ELIMINATE factors that no longer add value. REDUCE factors below standard. RAISE factors above standard. CREATE factors never offered before. Apply all four simultaneously for value innovation.", sourceType:"book", sourceName:"Blue Ocean Strategy", tags:["blue-ocean","strategy"], confidence:0.9 },
  { category:"strategy", title:"Six Paths Framework", content:"1) Alternative industries, 2) Strategic groups, 3) Buyer chain, 4) Complementary offerings, 5) Functional-emotional orientation, 6) Time/trends. Each path reveals uncontested market space.", sourceType:"book", sourceName:"Blue Ocean Strategy", tags:["blue-ocean","strategy","sales"], confidence:0.85 },
  { category:"strategy", title:"Three Tiers of Noncustomers", content:"Tier 1: soon-to-leave customers (fix their reason). Tier 2: refusing noncustomers (address their barrier). Tier 3: unexplored noncustomers (create new value for them). Focus on noncustomers, not existing customers.", sourceType:"book", sourceName:"Blue Ocean Strategy", tags:["blue-ocean","strategy","sales"], confidence:0.85 },
  { category:"strategy", title:"Strategy Canvas", content:"Visual diagnostic: horizontal = factors industry competes on, vertical = offering level. Plot your value curve vs competitors. Where you diverge = blue ocean opportunity.", sourceType:"book", sourceName:"Blue Ocean Strategy", tags:["blue-ocean","strategy"], confidence:0.85 },
  { category:"strategy", title:"Buyer Utility Map — 6 Stages", content:"Purchase, Delivery, Use, Supplements, Maintenance, Disposal. For each stage: identify utility blockers and remove them. Create extraordinary utility at every step.", sourceType:"book", sourceName:"Blue Ocean Strategy", tags:["blue-ocean","strategy"], confidence:0.8 },
  { category:"strategy", title:"Price Corridor of the Mass", content:"Set price to attract the mass of target buyers. Check 3 references: substitutes, competitors, look-alike products. Price for mass appeal while ensuring profit.", sourceType:"book", sourceName:"Blue Ocean Strategy", tags:["blue-ocean","strategy","pricing"], confidence:0.8 },
  { category:"strategy", title:"Tipping Point Leadership", content:"Overcome 4 hurdles: COGNITIVE (show reality), RESOURCE (concentrate), MOTIVATIONAL (win influencers first), POLITICAL (neutralize opposition). Focus on 20% that drives 80%.", sourceType:"book", sourceName:"Blue Ocean Strategy", tags:["blue-ocean","strategy","leadership"], confidence:0.85 },
  { category:"strategy", title:"Fair Process — 3E Principle", content:"ENGAGEMENT (involve people), EXPLANATION (explain why), EXPECTATION CLARITY (clear rules). Fair Process builds trust and voluntary cooperation even during difficult decisions.", sourceType:"book", sourceName:"Blue Ocean Strategy", tags:["blue-ocean","strategy","trust"], confidence:0.85 },
  { category:"strategy", title:"Pioneer-Migrator-Settler (PMS) Map", content:"Settlers (me-too, minimize), Migrators (better but not unique, upgrade), Pioneers (unprecedented value, invest). Aim: 20% pioneers, 60% migrators, 20% settlers.", sourceType:"book", sourceName:"Blue Ocean Strategy", tags:["blue-ocean","strategy"], confidence:0.85 },
  { category:"strategy", title:"Strategic Sequencing", content:"Validate in order: 1) Buyer Utility, 2) Price, 3) Cost, 4) Adoption. Skip any step and risk failure. Only proceed when current step is confirmed.", sourceType:"book", sourceName:"Blue Ocean Strategy", tags:["blue-ocean","strategy"], confidence:0.85 },
  { category:"strategy", title:"Red Ocean Traps to Avoid", content:"Trap 1: 'Be best in industry' (change industry instead). Trap 2: 'Differentiation costs more' (value innovation achieves both). Trap 3: 'Customers define market' (lead them to new value).", sourceType:"book", sourceName:"Blue Ocean Strategy", tags:["blue-ocean","strategy","sales"], confidence:0.85 },
  { category:"sales", title:"Blue Ocean Selling — Don't Compete, Create", content:"Don't compare with competitors. Frame product as creating NEW value. Use ERRC thinking. Price for mass appeal. Show value at EVERY step of buyer journey.", sourceType:"book", sourceName:"Blue Ocean Strategy", tags:["blue-ocean","sales"], confidence:0.85 },
  { category:"sales", title:"Six Paths — Sales Exploration", content:"When lead says 'I'm comparing options,' use Six Paths: alternative industries, strategic groups, buyer chain, complementary, emotional, time/future. Differentiate by creating new value, not beating competitors.", sourceType:"book", sourceName:"Blue Ocean Strategy", tags:["blue-ocean","sales"], confidence:0.85 },
  { category:"sales", title:"Three Tiers — Convert Noncustomers", content:"Tier 1 (inactive members): fix the ONE thing that disappointed. Tier 2 (refused to join): remove trust barrier, not price. Tier 3 (never considered): create new value proposition for them.", sourceType:"book", sourceName:"Blue Ocean Strategy", tags:["blue-ocean","sales"], confidence:0.85 },

  // ═══════════════════════════════════════════════════
  // BOOK: Psychology of Selling — Brian Tracy
  // ═══════════════════════════════════════════════════
  { category:"sales", title:"Inner Game / Self-Concept", content:"80/20 rule: 20% of salespeople earn 80% of income. Difference is self-concept. A salesperson who sees themselves as a $50k earner will behave accordingly. Reset the financial thermostat.", sourceType:"book", sourceName:"The Psychology of Selling by Brian Tracy", tags:["brian-tracy","sales","psychology"], confidence:0.85 },
  { category:"sales", title:"Seven Key Result Areas (KRAs)", content:"1) Prospecting, 2) Building Rapport, 3) Identifying Needs, 4) Presenting, 5) Answering Objections, 6) Closing, 7) Getting Resales & Referrals. Weakness in ANY ONE limits total success.", sourceType:"book", sourceName:"The Psychology of Selling by Brian Tracy", tags:["brian-tracy","sales"], confidence:0.85 },
  { category:"sales", title:"Goal Setting & Visualization", content:"Written goals have power. Goals cascade: Annual Income -> Annual Sales -> Monthly -> Weekly -> Daily -> Activity. Write 100 goals. Visualize success daily. Subconscious mind finds ways to achieve visualized goals.", sourceType:"book", sourceName:"The Psychology of Selling by Brian Tracy", tags:["brian-tracy","sales","psychology"], confidence:0.8 },
  { category:"sales", title:"Why People Buy — Gain vs Fear", content:"Two core motivations: Desire for Gain (power=1.0) and Fear of Loss (power=2.5x stronger). Always leverage BOTH. Fear of loss is 2.5x more powerful than desire for gain.", sourceType:"book", sourceName:"The Psychology of Selling by Brian Tracy", tags:["brian-tracy","sales","psychology"], confidence:0.9 },
  { category:"sales", title:"11 Primary Customer Needs", content:"Money, Security, Being Liked, Status & Prestige, Health & Fitness, Praise & Recognition, Power & Influence, Leading the Field, Love & Companionship, Personal Growth, Personal Transformation. Find the primary need and connect your offer to it.", sourceType:"book", sourceName:"The Psychology of Selling by Brian Tracy", tags:["brian-tracy","sales"], confidence:0.85 },
  { category:"sales", title:"Six Buyer Personality Types", content:"1) Apathetic — don't waste time, 2) Self-Actualizing — don't oversell, 3) Analytical — prove everything, 4) Relater — build relationship, 5) Driver — be direct, 6) Socialized — focus on recognition. Speak their language.", sourceType:"book", sourceName:"The Psychology of Selling by Brian Tracy", tags:["brian-tracy","sales","psychology"], confidence:0.85 },
  { category:"sales", title:"Feel-Felt-Found Method", content:"Most powerful objection handler: 'I understand how you feel (Feel). Many clients felt the same (Felt). But they found that (Found)...' Validates emotion, shows they're not alone, provides proof. Never argue — acknowledge first.", sourceType:"book", sourceName:"The Psychology of Selling by Brian Tracy", tags:["brian-tracy","sales","communication"], confidence:0.9 },
  { category:"sales", title:"Benefits Not Features", content:"People don't buy features — they buy BENEFITS. Every feature must become a benefit. For every 1 feature, give 10 benefits. '40 videos' -> 'learn at your own pace, anytime, anywhere.'", sourceType:"book", sourceName:"The Psychology of Selling by Brian Tracy", tags:["brian-tracy","sales","communication"], confidence:0.85 },
  { category:"sales", title:"Assumptive Close", content:"Act as if customer has ALREADY decided. 'Shall we start with Standard or Premium?' Not 'Will you buy?' but 'Which one?' Makes decision feel natural and expected.", sourceType:"book", sourceName:"The Psychology of Selling by Brian Tracy", tags:["brian-tracy","sales"], confidence:0.8 },
  { category:"sales", title:"Alternative Choice Close", content:"Give two options — BOTH lead to purchase. 'Monthly or yearly?' 'Online or offline?' Brain prefers choosing between options over Yes/No. Choice = control = comfort = decision.", sourceType:"book", sourceName:"The Psychology of Selling by Brian Tracy", tags:["brian-tracy","sales"], confidence:0.8 },
  { category:"sales", title:"30-Second Rule", content:"You have 30 seconds to grab attention. First break preoccupation, THEN deliver value. Never start selling immediately — sell the APPOINTMENT, not the product on first contact.", sourceType:"book", sourceName:"The Psychology of Selling by Brian Tracy", tags:["brian-tracy","sales","communication"], confidence:0.8 },
  { category:"sales", title:"Power of Suggestion", content:"Your appearance, environment, attitude suggest your value. Professional presentation = credibility. In Bangladesh, trustworthiness is especially important — your presentation is the first impression.", sourceType:"book", sourceName:"The Psychology of Selling by Brian Tracy", tags:["brian-tracy","sales"], confidence:0.75 },
  { category:"sales", title:"10 Keys to Success", content:"1) Do what you love, 2) Decide what you want, 3) Persistence, 4) Lifelong Learning, 5) Use time well, 6) Follow the leader, 7) Character is everything, 8) Unlock creativity, 9) Golden Rule, 10) Pay the price.", sourceType:"book", sourceName:"The Psychology of Selling by Brian Tracy", tags:["brian-tracy","sales","success"], confidence:0.75 },
  { category:"sales", title:"Gain vs Fear Framing", content:"Frame with BOTH gain AND fear of loss. Gain: 'You can earn 50,000 TK/month.' Fear: 'Without this, you're losing 50,000 TK/month you could have.' Fear is 2.5x more powerful. Always show the solution too.", sourceType:"book", sourceName:"The Psychology of Selling by Brian Tracy", tags:["brian-tracy","sales","psychology"], confidence:0.85 },

  // ═══════════════════════════════════════════════════
  // BOOK: Marketing Management — Philip Kotler
  // ═══════════════════════════════════════════════════
  { category:"marketing", title:"STP Framework — Segmentation-Targeting-Positioning", content:"SEGMENT: Geographic, Demographic, Psychographic, Behavioral. TARGET: use 5 criteria (Measurable, Substantial, Accessible, Differentiable, Actionable). POSITION: use POD (Points of Difference) and POP (Points of Parity).", sourceType:"book", sourceName:"Marketing Management by Philip Kotler", tags:["kotler","marketing","strategy"], confidence:0.9 },
  { category:"marketing", title:"Value Proposition Canvas", content:"Map customer PROFILE (jobs, pains, gains) and your VALUE (products, pain relievers, gain creators). A clear value proposition doubles conversion. Understand what the customer needs before presenting solutions.", sourceType:"book", sourceName:"Marketing Management by Philip Kotler", tags:["kotler","marketing","sales"], confidence:0.85 },
  { category:"marketing", title:"CBBE Brand Pyramid", content:"6 levels: 1) Salience (awareness), 2) Performance (features), 3) Imagery (image), 4) Judgments (quality), 5) Feelings (emotion), 6) Resonance (loyalty/community). Move customers from Salience to Resonance.", sourceType:"book", sourceName:"Marketing Management by Philip Kotler", tags:["kotler","marketing","brand"], confidence:0.85 },
  { category:"marketing", title:"SERVQUAL Service Quality Model", content:"5 dimensions: Tangibility (look), Reliability (dependability), Responsiveness (speed), Assurance (trust), Empathy (care). Excel in all 5 in every customer interaction.", sourceType:"book", sourceName:"Marketing Management by Philip Kotler", tags:["kotler","marketing","service"], confidence:0.85 },
  { category:"marketing", title:"Service Recovery Paradox", content:"Customers who experience a problem that is RESOLVED perfectly can become MORE loyal than those who never had a problem. 4 steps: Acknowledge -> Apologize -> Fix -> Follow up.", sourceType:"book", sourceName:"Marketing Management by Philip Kotler", tags:["kotler","marketing","service","trust"], confidence:0.85 },
  { category:"marketing", title:"Consumer Behavior Model", content:"4 factors influence buying: Cultural, Social, Personal, Psychological. 5-stage decision: Problem Recognition -> Information Search -> Evaluation -> Purchase -> Post-Purchase. Identify which stage the customer is in.", sourceType:"book", sourceName:"Marketing Management by Philip Kotler", tags:["kotler","marketing","psychology"], confidence:0.85 },
  { category:"marketing", title:"IMC — Integrated Marketing Communications", content:"8 channels: Advertising, PR, Sales Promotion, Direct Marketing, Digital/Social, Events, Personal Selling, Word-of-Mouth. All channels must speak with ONE voice.", sourceType:"book", sourceName:"Marketing Management by Philip Kotler", tags:["kotler","marketing","communication"], confidence:0.8 },
  { category:"marketing", title:"AIDA Campaign Model", content:"ATTENTION (bold headline), INTEREST (relevant benefit), DESIRE (social proof/emotion), ACTION (clear CTA). Every campaign follows this sequence.", sourceType:"book", sourceName:"Marketing Management by Philip Kotler", tags:["kotler","marketing","sales"], confidence:0.8 },
  { category:"marketing", title:"7-Step Personal Selling Process", content:"1) Prospecting, 2) Preapproach, 3) Approach, 4) Presentation, 5) Handling Objections, 6) Closing, 7) Follow-Up. Master every step from prospecting to follow-up.", sourceType:"book", sourceName:"Marketing Management by Philip Kotler", tags:["kotler","marketing","sales"], confidence:0.8 },
  { category:"marketing", title:"Ansoff Growth Matrix", content:"4 strategies: Market Penetration (existing product+market), Market Development (new market), Product Development (new product), Diversification (new both). Penetration = lowest risk, Diversification = highest.", sourceType:"book", sourceName:"Marketing Management by Philip Kotler", tags:["kotler","marketing","strategy"], confidence:0.85 },
  { category:"marketing", title:"Product Life Cycle (PLC)", content:"4 stages: Introduction (build awareness), Growth (build share), Maturity (defend share), Decline (harvest/divest). Each stage needs different marketing strategy.", sourceType:"book", sourceName:"Marketing Management by Philip Kotler", tags:["kotler","marketing","strategy"], confidence:0.85 },
  { category:"marketing", title:"CLV — Customer Lifetime Value", content:"CLV = Avg Purchase x Frequency x Lifetime. Loyal customers are 5-10x more valuable than new ones. Invest in retention, not just acquisition.", sourceType:"book", sourceName:"Marketing Management by Philip Kotler", tags:["kotler","marketing","strategy"], confidence:0.85 },
  { category:"marketing", title:"Diffusion of Innovation", content:"5 adopter categories: Innovators (2.5%), Early Adopters (13.5%), Early Majority (34%), Late Majority (34%), Laggards (16%). Launch targeting Innovators + Early Adopters first.", sourceType:"book", sourceName:"Marketing Management by Philip Kotler", tags:["kotler","marketing","strategy"], confidence:0.8 },

  // ═══════════════════════════════════════════════════
  // BOOK: Influence — Robert Cialdini (original)
  // ═══════════════════════════════════════════════════
  { category:"psychology", title:"Reciprocity", content:"Give FIRST before any ask. Free value, tip, compliment, resource. Human nature demands returning favors. The giver sets the terms of exchange.", sourceType:"book", sourceName:"Influence: The Psychology of Persuasion by Robert Cialdini", tags:["cialdini","psychology","sales"], confidence:0.9 },
  { category:"psychology", title:"Scarcity", content:"People want MORE of what they can have LESS of. Genuinely limited time/spots/bonuses. Never fake scarcity — it destroys trust permanently. 'This offer is available for 24 hours.'", sourceType:"book", sourceName:"Influence by Robert Cialdini", tags:["cialdini","psychology","sales"], confidence:0.85 },
  { category:"psychology", title:"Authority", content:"People follow credible experts. Establish through credentials, experience, numbers served. 'We've helped 10,000+ members.' Share confidently, not arrogantly.", sourceType:"book", sourceName:"Influence by Robert Cialdini", tags:["cialdini","psychology","trust"], confidence:0.85 },
  { category:"psychology", title:"Consistency", content:"Get small YES commitments that align with their values. 'You want the best for your family, right?' Then the larger ask naturally follows. Past behavior predicts future behavior.", sourceType:"book", sourceName:"Influence by Robert Cialdini", tags:["cialdini","psychology","sales"], confidence:0.85 },
  { category:"psychology", title:"Liking", content:"People say YES to people they LIKE. Build through genuine similarity, compliments, cooperation, familiarity. Similarity breeds connection.", sourceType:"book", sourceName:"Influence by Robert Cialdini", tags:["cialdini","psychology","communication"], confidence:0.85 },
  { category:"psychology", title:"Social Proof", content:"People follow the actions of similar others. 'Many in your situation succeeded with us.' Use stories of people LIKE them, not celebrities.", sourceType:"book", sourceName:"Influence by Robert Cialdini", tags:["cialdini","psychology","sales"], confidence:0.85 },
  { category:"psychology", title:"Pre-suasion", content:"WHAT you say matters less than what you say BEFORE. Prime the mind before main message. Before asking about purchase, prime 'growth'. Before trust, prime 'family'. The moment before shapes reception.", sourceType:"book", sourceName:"Pre-suasion by Robert Cialdini", tags:["cialdini","psychology","communication"], confidence:0.85 },

  // ═══════════════════════════════════════════════════
  // BOOK: The Courage to Be Disliked — Adlerian Psychology
  // ═══════════════════════════════════════════════════
  { category:"psychology", title:"Trauma Denial — Past Doesn't Define You", content:"Trauma does NOT control the present. When customer says 'I can't because of my past', reframe: 'Your past doesn't define you. You can choose differently now.' Empower responsibility for present choices.", sourceType:"book", sourceName:"The Courage to Be Disliked by Kishimi & Koga", tags:["adler","psychology","motivation"], confidence:0.85 },
  { category:"psychology", title:"Interpersonal Root — Belonging", content:"Every problem is ultimately a relationship problem. The customer's real need is BELONGING — to be accepted, valued, connected. Address the belonging need, not just the surface request.", sourceType:"book", sourceName:"The Courage to Be Disliked by Kishimi & Koga", tags:["adler","psychology","communication"], confidence:0.85 },
  { category:"psychology", title:"Task Separation — Freedom Through Boundaries", content:"What others think is THEIR task, not yours. Your task is to live by your values. 'What others think is their task. What you want for your life is your task.' Freedom comes from task separation.", sourceType:"book", sourceName:"The Courage to Be Disliked by Kishimi & Koga", tags:["adler","psychology","trust"], confidence:0.85 },
  { category:"psychology", title:"Not Center of World — Community Feeling", content:"You are not the center of the world. True belonging comes from contributing to the community. 'You are here to contribute, to connect, to grow together.' Shift focus from self to community (Gemeinschaftsgefuhl).", sourceType:"book", sourceName:"The Courage to Be Disliked by Kishimi & Koga", tags:["adler","psychology","community"], confidence:0.8 },
  { category:"psychology", title:"Here and Now — Happiness is Now", content:"Happiness is not in the future or past. Life is a dance, not a marathon. Every moment lived fully IS the destination. 'Don't wait for success to be happy. Be happy NOW.' Present focus reduces anxiety.", sourceType:"book", sourceName:"The Courage to Be Disliked by Kishimi & Koga", tags:["adler","psychology","motivation"], confidence:0.85 },
  { category:"psychology", title:"Horizontal Relationships — Equality", content:"Adler rejects vertical (superior/inferior) and promotes horizontal (EQUAL) relationships. Treat every customer as EQUAL. 'I am not your boss or servant. We are two humans walking together.' Never talk down.", sourceType:"book", sourceName:"The Courage to Be Disliked by Kishimi & Koga", tags:["adler","psychology","trust"], confidence:0.85 },
  { category:"psychology", title:"Courage to Be Disliked — True Freedom", content:"True freedom = courage to be disliked. If you live by everyone's approval, you live by everyone's control. 'You cannot please everyone — you don't need to.' Make decisions aligned with YOUR values.", sourceType:"book", sourceName:"The Courage to Be Disliked by Kishimi & Koga", tags:["adler","psychology","trust"], confidence:0.85 },
  { category:"psychology", title:"Encouragement Not Praise", content:"Praise creates dependency ('I am good because you say so'). Encouragement creates self-reliance ('I am good because I tried'). Say 'You worked hard — that matters' not 'You're amazing.'", sourceType:"book", sourceName:"The Courage to Be Disliked by Kishimi & Koga", tags:["adler","psychology","communication"], confidence:0.85 },
  { category:"psychology", title:"Personal Responsibility — You Are the Change", content:"Your life is YOUR responsibility. Not your past, not your environment, not others — YOU. And this is empowering: because responsibility is yours, change is also yours. No one can save you but you.", sourceType:"book", sourceName:"The Courage to Be Disliked by Kishimi & Koga", tags:["adler","psychology","motivation"], confidence:0.85 },

  // ═══════════════════════════════════════════════════
  // BOOK: Predictably Irrational — Dan Ariely
  // ═══════════════════════════════════════════════════
  { category:"psychology", title:"Pain of Paying", content:"People feel PAIN when paying. Reduce pain: break price into daily cost ('only 14 TK/day'), offer installments, compare to daily expenses ('less than a cup of tea'). NEVER state total price without framing first.", sourceType:"book", sourceName:"Predictably Irrational by Dan Ariely", tags:["ariely","psychology","pricing"], confidence:0.85 },
  { category:"psychology", title:"Decoy Effect — Asymmetric Dominance", content:"Offer 3 options where middle is your target. Example: Basic (500), Standard (1500 — target), Premium (3000). Premium makes Standard look reasonable. Basic makes Standard look valuable. Always structure 3+ options.", sourceType:"book", sourceName:"Predictably Irrational by Dan Ariely", tags:["ariely","psychology","pricing","sales"], confidence:0.85 },
  { category:"psychology", title:"Anchoring — First Number Sets the Bar", content:"Start HIGHER than your target, then present real offer. 'Premium is 10,000 TK, but today you get it for 3,000 TK.' Contrast makes real price feel like a deal. Never start with lowest price — lose anchor advantage.", sourceType:"book", sourceName:"Predictably Irrational by Dan Ariely", tags:["ariely","psychology","pricing","sales"], confidence:0.85 },
  { category:"psychology", title:"Tightwad vs Spendthrift", content:"Tightwads: emphasize savings, ROI, low risk. Spendthrifts: emphasize premium, exclusive, quality. Detect from their language. Frame SAME price differently based on their style.", sourceType:"book", sourceName:"Predictably Irrational by Dan Ariely", tags:["ariely","psychology","pricing","sales"], confidence:0.8 },
  { category:"psychology", title:"Per-Day Framing", content:"ALWAYS convert large numbers to daily cost. '5000 TK' -> 'Only 14 TK/day — less than a cup of tea.' Smaller unit reduces pain of paying. Most powerful neuromarketing price technique.", sourceType:"book", sourceName:"Predictably Irrational by Dan Ariely", tags:["ariely","psychology","pricing","sales"], confidence:0.85 },

  // ═══════════════════════════════════════════════════
  // BOOK: Brainfluence — Roger Dooley
  // ═══════════════════════════════════════════════════
  { category:"marketing", title:"Right Ear Technique", content:"The right ear processes language better (left brain = language center). Important information delivered to RIGHT ear increases recall. For text: put most important info on RIGHT side of message.", sourceType:"book", sourceName:"Brainfluence by Roger Dooley", tags:["dooley","marketing","neuromarketing"], confidence:0.75 },
  { category:"marketing", title:"Simplicity Over Complexity", content:"Complex products sell better with SIMPLE messages. One line, one benefit, one emotion. 'A course that will change your life.' '15 min daily, income for life.' Simple = System 1 friendly. Complex = rejection.", sourceType:"book", sourceName:"Brainfluence by Roger Dooley", tags:["dooley","marketing","communication"], confidence:0.8 },
  { category:"marketing", title:"Visual Language — 6x More Memorable", content:"Use vivid visual language: 'Imagine waking up, checking your phone, seeing 500 TK deposited overnight.' Visual language activates visual cortex — makes message 6x more memorable.", sourceType:"book", sourceName:"Brainfluence by Roger Dooley", tags:["dooley","marketing","communication"], confidence:0.8 },
  { category:"marketing", title:"Emotional Imagery — Sensory Words", content:"Use words that evoke sensory experience: warmth (family, security), brightness (future, dream), texture (smooth, easy). Sensory words trigger real brain responses.", sourceType:"book", sourceName:"Brainfluence by Roger Dooley", tags:["dooley","marketing","communication"], confidence:0.75 },
  { category:"marketing", title:"Baby Image Effect", content:"Images of babies/children trigger automatic care response. Mention children/family warmly: 'Your child's future' 'Doing something for family.' Triggers automatic emotional response bypassing logical defenses.", sourceType:"book", sourceName:"Brainfluence by Roger Dooley", tags:["dooley","marketing","psychology"], confidence:0.75 },

  // ═══════════════════════════════════════════════════
  // BOOK: OXYTOCIN Trust — Paul Zak
  // ═══════════════════════════════════════════════════
  { category:"psychology", title:"Character-Driven Story — 3-Act Structure", content:"1) Relatable character facing challenge (cortisol -> attention), 2) Empathy/connection (oxytocin -> trust), 3) Positive resolution (dopamine -> reward). This structure increases oxytocin 50% and boosts trust dramatically.", sourceType:"book", sourceName:"The Ethical DNA / OXYTOCIN Trust by Paul Zak", tags:["zak","psychology","trust","communication"], confidence:0.85 },
  { category:"psychology", title:"Cortisol Blocks Oxytocin — Reduce Stress First", content:"If they're stressed/scared, they CANNOT bond with you. First reduce cortisol: validate their fear, make them feel safe, remove pressure. THEN build oxytocin: empathy, shared experience, genuine care.", sourceType:"book", sourceName:"OXYTOCIN Trust by Paul Zak", tags:["zak","psychology","trust"], confidence:0.85 },
  { category:"psychology", title:"Paul Zak's 8 OXYTOCIN Behaviors", content:"1) Ovation (praise effort), 2) eXpectation (clear goals), 3) Yield (give autonomy), 4) Transfer (entrust responsibility), 5) Openness (share transparently), 6) Caring (show genuine interest), 7) Invest (develop skills), 8) Natural (be authentic).", sourceType:"book", sourceName:"OXYTOCIN Trust by Paul Zak", tags:["zak","psychology","trust","leadership"], confidence:0.85 },

  // ═══════════════════════════════════════════════════
  // BOOK: Thinking, Fast and Slow — Kahneman
  // ═══════════════════════════════════════════════════
  { category:"psychology", title:"System 1 First — Hook Emotion Before Logic", content:"95% of decisions by System 1 (fast, emotional, subconscious). First 3 seconds must hook System 1: simple language, short sentences, emotional connection, vivid imagery. THEN serve System 2 with details.", sourceType:"book", sourceName:"Thinking, Fast and Slow by Daniel Kahneman", tags:["kahneman","psychology","communication","sales"], confidence:0.85 },
  { category:"psychology", title:"System 2 Pain — When to Use Logic", content:"Complex info (pricing, comparisons) must come AFTER emotional safety. If fast replies -> System 1 mode -> stay emotional. If analytical questions -> switch to System 2. Match their current system.", sourceType:"book", sourceName:"Thinking, Fast and Slow by Daniel Kahneman", tags:["kahneman","psychology","communication"], confidence:0.85 },
  { category:"psychology", title:"Hook-Anchor — Open Every Message", content:"Open every message with a System 1 hook: vivid image, emotional question, relatable scenario. 'Imagine...' 'Have you ever thought...' THEN follow with System 2 substance.", sourceType:"book", sourceName:"Thinking, Fast and Slow by Daniel Kahneman", tags:["kahneman","psychology","communication"], confidence:0.8 },
  { category:"psychology", title:"Hot vs Cold State — Emotion First", content:"System 1 = hot state (emotional, impulsive). System 2 = cold state (calm, rational). When in hot state (excited, scared, angry), DO NOT present complicated options. Validate emotion first. Guide to cold state before reasoning.", sourceType:"book", sourceName:"Thinking, Fast and Slow by Daniel Kahneman", tags:["kahneman","psychology","communication"], confidence:0.85 },
  { category:"psychology", title:"Default to System 1 Communication", content:"Default: emotional safety -> vivid imagery -> social proof -> simple choice. Add System 2 (data, comparisons, specs) only when person explicitly asks or shows analytical communication style.", sourceType:"book", sourceName:"Thinking, Fast and Slow by Daniel Kahneman", tags:["kahneman","psychology","communication","sales"], confidence:0.85 },

  // ═══════════════════════════════════════════════════
  // BOOK: Positioning — Ries & Trout
  // ═══════════════════════════════════════════════════
  { category:"marketing", title:"Positioning — Battle for the Mind", content:"Positioning is not about what YOU do to the product — it's what you do to the MIND of the prospect. Position your offering in the customer's mind relative to competitors. Find a mental space no one else owns.", sourceType:"book", sourceName:"Positioning: The Battle for Your Mind by Ries & Trout", tags:["ries-trout","marketing","strategy"], confidence:0.85 },

  // ═══════════════════════════════════════════════════
  // EXTRA: System entries (Transparency, Choice Paradox, NPS, etc.)
  // ═══════════════════════════════════════════════════
  { category:"trust", title:"Behind-the-Scenes Transparency", content:"People trust what they can SEE. Mention the real people behind the business. Admit when you don't know something. Explicitly mention privacy protection. Share HOW decisions are made. Visible team = trustworthy. Hidden = suspicious.", sourceType:"system", sourceName:"Harvard Transparency Research — Dennis Campbell", tags:["transparency","trust"], confidence:0.85 },
  { category:"psychology", title:"Choice Paradox — Less is More", content:"Too many options PARALYZE customers. Every extra option reduces conversion by 10%. Never present more than 3 options at once. Curate and recommend. Progressive disclosure: reveal info step by step.", sourceType:"system", sourceName:"The Paradox of Choice by Barry Schwartz", tags:["choice-paradox","psychology","sales"], confidence:0.85 },
  { category:"marketing", title:"NPS & Peer Recommendation", content:"78% of people buy based on peer recommendations. Only 14% trust ads. Use real customer testimonials, not marketing copy. Frame referrals as helping friends, not selling. Promoters (NPS 9-10) are your best salespeople.", sourceType:"system", sourceName:"Net Promoter System", tags:["nps","marketing","sales"], confidence:0.8 },
  { category:"psychology", title:"Loss Aversion — Frame Inaction as Loss", content:"Frame inaction as missing out on a proven opportunity. 'Not joining means you're leaving money on the table — money that could change your family's future.' Fear of loss is 2.5x more powerful than desire for gain.", sourceType:"system", sourceName:"Customer Psychology — Loss Aversion", tags:["psychology","sales"], confidence:0.8 },
  { category:"psychology", title:"NLP Mirroring & Rapport", content:"Mirror the person's language style, tone, key words. If they use Banglish, respond in Banglish. If urgent, match urgency. If calm, stay calm. Matching builds unconscious rapport.", sourceType:"system", sourceName:"NLP Communication Techniques", tags:["nlp","psychology","communication"], confidence:0.8 },
  { category:"psychology", title:"NLP VAK Model — Visual/Auditory/Kinesthetic", content:"Use Visual ('see', 'imagine'), Auditory ('hear', 'sounds'), or Kinesthetic ('feel', 'grasp') language based on their cues. Match their preferred representational system for deeper connection.", sourceType:"system", sourceName:"NLP Communication Techniques", tags:["nlp","psychology","communication"], confidence:0.75 },
  { category:"psychology", title:"Anchoring Positive Emotions", content:"When someone expresses positive emotion (excitement, hope), acknowledge it strongly so they associate that feeling with the conversation and with you. Emotional anchoring builds lasting positive association.", sourceType:"system", sourceName:"NLP Anchoring Technique", tags:["nlp","psychology"], confidence:0.75 },
  { category:"communication", title:"F/Z Visual Scanning Pattern", content:"Structure messages for optimal eye scan: F-pattern for text (most important at top-left), Z-pattern for simple messages (hook->image->proof->CTA). Use short paragraphs (1-3 lines). White space = cognitive ease.", sourceType:"system", sourceName:"Neuromarketing Eye Tracking Research", tags:["neuromarketing","communication"], confidence:0.75 },
  { category:"communication", title:"Attention Hierarchy — Structure Every Message", content:"Line 1 = EMOTIONAL HOOK. Lines 2-4 = KEY POINTS. Last line = CLEAR CTA. Top gets most attention. NEVER put CTA in middle. Always at very end or very beginning.", sourceType:"system", sourceName:"Neuromarketing Attention Research", tags:["neuromarketing","communication"], confidence:0.75 },

  // ═══════════════════════════════════════════════════
  // TRAINING MODULES
  // ═══════════════════════════════════════════════════
  { category:"psychology", title:"Personal Connection First (Onboarding)", content:"When a new member registers, do NOT start with offers. First 24 hours: build personal connection. Ask about their family, goals, dreams. Show them they are part of a family, not a sales machine.", sourceType:"training", sourceName:"Member Onboarding Guide", tags:["onboarding","psychology","trust"], confidence:0.9 },
  { category:"sales", title:"Value First — Give Before Asking (Onboarding)", content:"New members should receive value before being asked to produce. Give free training, tips, encouragement. Only after they experience value, introduce income opportunities.", sourceType:"training", sourceName:"Member Onboarding Guide", tags:["onboarding","sales","trust"], confidence:0.9 },
  { category:"trust", title:"Income is a Tool, Not a Goal (Onboarding)", content:"Frame income as a tool for life transformation. 'You're not just earning 500 TK — you're earning a tool for your child's education, your family's health.' Connect money to meaning.", sourceType:"training", sourceName:"Member Onboarding Guide", tags:["onboarding","trust","psychology"], confidence:0.85 },
  { category:"psychology", title:"Celebrate Every Win (Motivation)", content:"When a member achieves something, celebrate genuinely. Connect achievement to their personal story. 'Remember when you joined with this dream? Today you took a step closer.' Make them feel seen.", sourceType:"training", sourceName:"Member Motivation Guide", tags:["motivation","psychology"], confidence:0.85 },
  { category:"trust", title:"Team Building is Family Building (Motivation)", content:"Frame team building as helping others grow, not recruiting. 'You're not building a downline — you're building a family.' Every person you bring is someone whose life you can change.", sourceType:"training", sourceName:"Member Motivation Guide", tags:["motivation","trust","sales"], confidence:0.85 },
  { category:"communication", title:"Speak Their Language — Sponsor Tips (Affiliate)", content:"Adapt communication: Students -> education/future. Homemakers -> family/security. Business owners -> ROI/growth. Never one-size-fits-all. Match their language, fears, dreams.", sourceType:"training", sourceName:"Affiliate Communication Guide", tags:["affiliate","communication","sales"], confidence:0.85 },
  { category:"sales", title:"Handle Resistance — We're Together (Affiliate)", content:"When team member resists, do NOT argue. 'I understand your doubt. Let's figure this out together.' Turn resistance into collaboration. Never push. Guide to their own conclusion.", sourceType:"training", sourceName:"Affiliate Communication Guide", tags:["affiliate","sales","communication"], confidence:0.85 },
  { category:"trust", title:"Premium is Family, Not Status", content:"Premium members are family, not just customers. Use Golden Rule: make them feel known, valued, seen. 'You're not just a premium member — you're a partner in our journey.'", sourceType:"training", sourceName:"Premium Experience Guide", tags:["premium","trust","psychology"], confidence:0.85 },
  { category:"psychology", title:"We Together — Premium Partnership", content:"Use 'We' framing: 'We are building your business together.' Premium members should feel they have a dedicated partner. Ask about goals. Celebrate wins. Make their success your success.", sourceType:"training", sourceName:"Premium Experience Guide", tags:["premium","psychology","trust"], confidence:0.85 },
  { category:"sales", title:"Value First, Then Upgrade (Premium Funnel)", content:"Before offering premium upgrade: 1) Show value — calculate savings. 2) Social proof — share upgrade stories. 3) Let them decide — 'Only if it feels right for your goals.' Never pressure.", sourceType:"training", sourceName:"Premium Upgrade Funnel", tags:["premium","sales","trust"], confidence:0.85 },
  { category:"communication", title:"Speak Their Language — Premium Benefits", content:"Different members value different benefits. Students: unlimited learning. Earners: zero withdrawal tax. Builders: priority support. Match benefit to their world.", sourceType:"training", sourceName:"Premium Upgrade Funnel", tags:["premium","communication","sales"], confidence:0.85 },

  // ═══════════════════════════════════════════════════
  // NEW BOOKS (from Phase 2 seed-books-2.ts):
  // Hooked, This Is Marketing, Influence (detailed)
  // ═══════════════════════════════════════════════════
  { category:"psychology", title:"The Habit Zone — Why Habits Matter", content:"Habits are automatic behaviors triggered by situational cues, guiding nearly half of our daily actions without conscious thought. Products that create strong habits enjoy: higher Customer Lifetime Value (CLTV), pricing flexibility, faster viral growth (shorter Viral Cycle Time), and a sharp competitive edge. The goal: connect user's problem to your solution frequently enough to form a habit.", sourceType:"book", sourceName:"Hooked: How to Build Habit-Forming Products by Nir Eyal", tags:["hooked","nir-eyal","habits","psychology","product"], confidence:0.9 },
  { category:"psychology", title:"Trigger — External & Internal", content:"Triggers are the actuator of behavior. Two types: EXTERNAL (email, app icon, link) and INTERNAL (emotions, routines, situations). Winning products start as external triggers and become associated with internal triggers. When users feel bored -> open Twitter. Lonely -> scroll Facebook. Question -> query Google. The first-to-mind solution wins.", sourceType:"book", sourceName:"Hooked by Nir Eyal", tags:["hooked","nir-eyal","triggers","psychology"], confidence:0.9 },
  { category:"psychology", title:"Action — Fogg Behavior Model", content:"Behavior = Motivation + Ability + Trigger (all three must be present). MOTIVATION: 3 Core Motivators — seek pleasure/avoid pain, seek hope/avoid fear, seek social acceptance/avoid rejection. ABILITY: 6 factors of simplicity — Time, Money, Physical Effort, Brain Cycles, Social Deviance, Non-Routine. Make it EASIER rather than boosting motivation.", sourceType:"book", sourceName:"Hooked by Nir Eyal", tags:["hooked","nir-eyal","action","motivation","ability","fogg"], confidence:0.85 },
  { category:"psychology", title:"Variable Reward — The Craving Engine", content:"What distinguishes a Hook from a plain feedback loop is CRAVING. Variable rewards trigger dopamine surges. Three types: 1) Tribe (social validation), 2) Hunt (resources), 3) Self (mastery). The variability, not the reward itself, drives engagement.", sourceType:"book", sourceName:"Hooked by Nir Eyal", tags:["hooked","nir-eyal","variable-reward","dopamine","psychology"], confidence:0.85 },
  { category:"psychology", title:"Investment — Storing Value", content:"The user puts something into the product (time, data, effort, social capital, money). This increases odds of future Hook cycles. Investments: invite friends, state preferences, build assets, learn features. Creates stored value that makes leaving harder.", sourceType:"book", sourceName:"Hooked by Nir Eyal", tags:["hooked","nir-eyal","investment","retention","psychology"], confidence:0.85 },
  { category:"psychology", title:"The Morality of Manipulation", content:"The Manipulation Matrix: does the creator use the product? Does it improve users' lives? Four quadrants: Facilitator, Peddler, Entertainer, Dealer. Aspire to be a Facilitator. Use choice architecture to nudge toward better decisions.", sourceType:"book", sourceName:"Hooked by Nir Eyal", tags:["hooked","nir-eyal","ethics","manipulation"], confidence:0.85 },
  { category:"strategy", title:"Habit Testing — 5 Questions", content:"1) What internal trigger? 2) What brings users in first 3 seconds? 3) Expected reward type? 4) What investment do users make? 5) What makes them come back? The Habit Test: if 5%+ return daily unprompted, you're on track.", sourceType:"book", sourceName:"Hooked by Nir Eyal", tags:["hooked","nir-eyal","testing","strategy"], confidence:0.85 },
  { category:"psychology", title:"The Bible App Case Study — Hook Model in Action", content:"YouVersion reached 100M+ downloads. TRIGGER: Daily reminders -> guilt/desire to connect. ACTION: Simple tap. VARIABLE REWARD: Different verse daily, community. INVESTMENT: Highlights, bookmarks, plans. Result: 80%+ return next day.", sourceType:"book", sourceName:"Hooked by Nir Eyal", tags:["hooked","nir-eyal","case-study","bible-app"], confidence:0.85 },
  { category:"marketing", title:"Marketing Is the Act of Making Change", content:"Marketing is making change happen. When you give a TED Talk, ask for a raise, raise money — you're marketing. Key question: 'Who can you help?' Marketing is the generous act of helping others change.", sourceType:"book", sourceName:"This Is Marketing by Seth Godin", tags:["godin","marketing","change"], confidence:0.9 },
  { category:"marketing", title:"The Smallest Viable Market", content:"Don't market to everyone. Market to the smallest viable audience. 'Who's it for?' is the most powerful question. Choose by WORLDVIEW (psychographics), not demographics. Start in a swimming pool, not the ocean.", sourceType:"book", sourceName:"This Is Marketing by Seth Godin", tags:["godin","marketing","audience","svma"], confidence:0.9 },
  { category:"marketing", title:"In Search of 'Better'", content:"'Better' is not universal. 250+ beers are someone's favorite. Empathy means accepting others don't want what you want. Your job: find a spot on the map that (some) people are looking for.", sourceType:"book", sourceName:"This Is Marketing by Seth Godin", tags:["godin","marketing","better","psychology"], confidence:0.85 },
  { category:"marketing", title:"Beyond Commodities — Status and Belonging", content:"People buy stories that signal status and create belonging. Key drivers: STATUS, AFFILIATION, IDENTITY. Frame your offer in terms of the status it confers and the community it grants access to.", sourceType:"book", sourceName:"This Is Marketing by Seth Godin", tags:["godin","marketing","status","belonging","community"], confidence:0.85 },
  { category:"marketing", title:"Trust and Tension Create Forward Motion", content:"Marketing creates change through tension and relief. CREATE TENSION: show the gap. RELIEVE TENSION: offer the bridge. Trust is the currency. Without trust, tension = manipulation. With trust, tension = a path forward.", sourceType:"book", sourceName:"This Is Marketing by Seth Godin", tags:["godin","marketing","trust","tension"], confidence:0.85 },
  { category:"marketing", title:"Price Is a Story", content:"Price is not a number — it's a story about value. Your pricing strategy IS your marketing strategy. Price for the story you want to tell, not the cost you want to cover.", sourceType:"book", sourceName:"This Is Marketing by Seth Godin", tags:["godin","marketing","pricing","story"], confidence:0.85 },
  { category:"marketing", title:"Permission and Remarkability", content:"PERMISSION: market to people who WANT to hear from you. REMARKABILITY: if it's not remarkable, it won't spread. The virtuous cycle: Permission -> Remarkability -> Sharing -> more Permission.", sourceType:"book", sourceName:"This Is Marketing by Seth Godin", tags:["godin","marketing","permission","remarkability"], confidence:0.85 },
  { category:"marketing", title:"Trust Is as Scarce as Attention", content:"How to earn trust: 1) Be consistent, 2) Be transparent, 3) Be generous, 4) Be reliable, 5) Be human. Trust is the foundation. Without it, nothing else matters.", sourceType:"book", sourceName:"This Is Marketing by Seth Godin", tags:["godin","marketing","trust","reputation"], confidence:0.85 },
  { category:"marketing", title:"The Funnel", content:"Customer journey: STRANGER -> INTERESTED -> COMMITTED -> CUSTOMER -> EVANGELIST. Each stage needs a different message. Most marketers fail by treating everyone at the top with the same message meant for the bottom.", sourceType:"book", sourceName:"This Is Marketing by Seth Godin", tags:["godin","marketing","funnel","customer-journey"], confidence:0.85 },
  { category:"marketing", title:"Organizing and Leading a Tribe", content:"Marketing is leadership. A tribe is connected to one another, a leader, and an idea. Your job: find shared identity, connect members, give status, make it easy to recruit others. Serve the tribe and it will grow.", sourceType:"book", sourceName:"This Is Marketing by Seth Godin", tags:["godin","marketing","tribe","leadership","community"], confidence:0.85 },
  { category:"psychology", title:"Weapons of Influence — Click-Whirr Automaticity", content:"Human behavior runs on fixed-action patterns triggered by specific features. The word 'because' triggers compliance. The contrast principle: expensive first makes next seem cheaper. Awareness is the first defense.", sourceType:"book", sourceName:"Influence: The Psychology of Persuasion by Robert Cialdini", tags:["cialdini","influence","psychology","automaticity"], confidence:0.9 },
  { category:"psychology", title:"Reciprocation — The Old Give and Take", content:"We must repay what is given. Universal across cultures. RECIPROCAL CONCESSION: make larger request first, get rejected, then real (smaller) request. Give FIRST before asking. The giver sets the terms.", sourceType:"book", sourceName:"Influence by Robert Cialdini", tags:["cialdini","influence","reciprocation","psychology"], confidence:0.9 },
  { category:"psychology", title:"Commitment and Consistency", content:"People want to be CONSISTENT with past commitments. Get a small initial commitment -> larger ones follow. WRITTEN > verbal. PUBLIC > private. ACTIVE > passive. Foot-in-the-door technique.", sourceType:"book", sourceName:"Influence by Robert Cialdini", tags:["cialdini","influence","consistency","commitment","psychology"], confidence:0.9 },
  { category:"psychology", title:"Social Proof — Truths Are Us", content:"People determine correctness by what others think — especially similar others. Works best under UNCERTAINTY and SIMILARITY. Show testimonials from similar customers. Always frame what people SHOULD do.", sourceType:"book", sourceName:"Influence by Robert Cialdini", tags:["cialdini","influence","social-proof","psychology"], confidence:0.9 },
  { category:"psychology", title:"Liking — The Friendly Thief", content:"People say YES to those they LIKE. Factors: attractiveness, similarity, compliments, cooperation, association. Tupperware model. Build genuine rapport before the ask.", sourceType:"book", sourceName:"Influence by Robert Cialdini", tags:["cialdini","influence","liking","psychology","rapport"], confidence:0.9 },
  { category:"psychology", title:"Authority — Directed Deference", content:"People defer to authority. Milgram experiment. Symbols: titles, clothing, trappings. Use ethically: establish genuine expertise. Beware of fake authority.", sourceType:"book", sourceName:"Influence by Robert Cialdini", tags:["cialdini","influence","authority","psychology"], confidence:0.9 },
  { category:"psychology", title:"Scarcity — The Rule of the Few", content:"Opportunities seem more valuable when limited. People want MORE of what they can have LESS of. NEW scarcity > existing scarcity. Competition magnifies effect. Never fake scarcity.", sourceType:"book", sourceName:"Influence by Robert Cialdini", tags:["cialdini","influence","scarcity","psychology"], confidence:0.9 },
];
