import type { DepartmentDef, DepartmentId, Intent } from "./types";

export const DEPARTMENTS: Record<DepartmentId, DepartmentDef> = {
  // ════════════════════════════════════════════
  // SALES & REVENUE
  // ════════════════════════════════════════════
  sales: {
    id: "sales",
    name: "Sales & Revenue",
    nameBn: "বিক্রয় ও রাজস্ব",
    icon: "💰",
    description: "Product sales, lead conversion, objection handling, campaigns",
    primaryModel: "gpt-4o",
    fallbackModels: ["claude-3.5-sonnet", "deepseek-chat"],
    teams: [
      // ─── Team 1.1: Lead Generation ───
      {
        id: "lead_gen",
        name: "Lead Generation",
        nameBn: "লিড জেনারেশন",
        department: "sales",
        description: "Find, score, classify and route leads",
        primaryModel: "gpt-4o-mini",
        fallbackModels: ["claude-3-haiku", "gemini-flash"],
        agents: [
          {
            id: "lead_scanner",
            name: "Lead Scanner",
            nameBn: "লিড স্ক্যানার",
            department: "sales",
            team: "lead_gen",
            description: "Scans conversation to detect purchase interest",
            descriptionBn: "কথোপকথন থেকে ক্রয় আগ্রহ শনাক্ত করে",
            expertise: "You detect if someone is interested in buying a product, joining as a member, or just browsing.",
            promptTemplate: "Analyze this message for purchase intent. Return one word: BUY/REGISTER/BROWSE/UNSURE. Consider Bangladeshi context: 'কত', 'দাম', 'যোগ দিতে চাই', 'কিনব', 'মembership', 'রেজি'. Only the word.",
            primaryModel: "gpt-4o-mini",
            fallbackModels: ["claude-3-haiku"],
            tier: 3,
            priority: 90,
            when: "intent === 'greeting' || intent === 'product_inquiry' || intent === 'general'",
          },
          {
            id: "lead_scorer",
            name: "Lead Scorer",
            nameBn: "লিড স্কোরার",
            department: "sales",
            team: "lead_gen",
            description: "Scores lead priority 0-10",
            descriptionBn: "লিডের অগ্রাধিকার স্কোর ০-১০",
            expertise: "You assign priority scores based on urgency, interest level, and purchase power signals.",
            promptTemplate: "Score this lead's priority from 0(very low) to 10(urgent/hot). Consider: payment questions, urgency words ('এখনই', 'তাড়াতাড়ি'), specific product interest, budget mention. Return only a number 0-10.",
            primaryModel: "gpt-4o-mini",
            fallbackModels: ["claude-3-haiku"],
            tier: 3,
            priority: 80,
            when: "intent === 'purchase' || intent === 'price_inquiry'",
          },
          {
            id: "lead_classifier",
            name: "Lead Classifier",
            nameBn: "লিড ক্লাসিফায়ার",
            department: "sales",
            team: "lead_gen",
            description: "Classifies leads as hot/warm/cold",
            descriptionBn: "লিডকে হট/ওয়ার্ম/কোল্ড এ ভাগ করে",
            expertise: "You classify leads: HOT (ready to buy, asking payment), WARM (interested, asking details), COLD (just browsing, no urgency).",
            promptTemplate: "Classify this lead as HOT/WARM/COLD. HOT = asking price/payment/registration. WARM = asking details/comparison. COLD = general chat, no intent. Return only the word.",
            primaryModel: "gpt-4o-mini",
            fallbackModels: ["claude-3-haiku"],
            tier: 3,
            priority: 70,
            when: "intent === 'purchase' || intent === 'price_inquiry' || intent === 'product_inquiry'",
          },
          {
            id: "lead_dispatcher",
            name: "Lead Dispatcher",
            nameBn: "লিড ডিসপ্যাচার",
            department: "sales",
            team: "lead_gen",
            description: "Routes hot leads to senior sales agent immediately",
            descriptionBn: "হট লিড দ্রুত সিনিয়র সেলে রুট করে",
            expertise: "You route leads: HOT → immediate senior attention, WARM → standard flow, COLD → nurture campaign.",
            promptTemplate: "Route this lead: if HOT → 'immediate', if WARM → 'standard', if COLD → 'nurture'. Return only the routing keyword.",
            primaryModel: "gpt-4o-mini",
            fallbackModels: ["claude-3-haiku"],
            tier: 4,
            priority: 60,
            when: "intent === 'purchase'",
          },
          {
            id: "source_tracker",
            name: "Source Tracker",
            nameBn: "সোর্স ট্র্যাকার",
            department: "sales",
            team: "lead_gen",
            description: "Tracks where the lead came from",
            descriptionBn: "লিড কোথা থেকে এসেছে তা ট্র্যাক করে",
            expertise: "You identify the source: WhatsApp direct, campaign, referral, website, or organic.",
            promptTemplate: "Detect source from context. Return one: whatsapp_direct / campaign / referral / website / organic / unknown.",
            primaryModel: "gpt-4o-mini",
            fallbackModels: ["claude-3-haiku"],
            tier: 4,
            priority: 40,
            when: "true",
          },
        ],
      },

      // ─── Team 1.2: Product Pitching ───
      {
        id: "product_pitch",
        name: "Product Pitching",
        nameBn: "পণ্য প্রেজেন্টেশন",
        department: "sales",
        description: "Match products, explain prices, highlight benefits",
        primaryModel: "claude-3.5-sonnet",
        fallbackModels: ["gpt-4o", "deepseek-chat"],
        agents: [
          {
            id: "product_matcher",
            name: "Product Matcher",
            nameBn: "পণ্য ম্যাচার",
            department: "sales",
            team: "product_pitch",
            description: "Matches customer needs to the right product",
            descriptionBn: "গ্রাহকের চাহিদার সাথে সঠিক পণ্য ম্যাচ করে",
            expertise: "You understand all products (MLM packages, courses, memberships) and match them to customer needs based on their message.",
            promptTemplate: "Based on the customer's message, suggest the most relevant product. Consider: budget signals ('কম দাম', 'সস্তা'), goal signals ('আয়', 'business', 'শিখতে'), status ('ছাত্র', 'চাকরি'). Return product name + 1-line reason in {{language}}.",
            primaryModel: "claude-3.5-sonnet",
            fallbackModels: ["gpt-4o", "deepseek-chat"],
            tier: 2,
            priority: 95,
            when: "intent === 'product_inquiry' || intent === 'price_inquiry'",
          },
          {
            id: "price_explainer",
            name: "Price Explainer",
            nameBn: "মূল্য ব্যাখ্যাকারী",
            department: "sales",
            team: "product_pitch",
            description: "Explains pricing, commissions, profit potential",
            descriptionBn: "দাম, কমিশন ও লাভের সম্ভাবনা ব্যাখ্যা করে",
            expertise: "You explain pricing in Bangladeshi context: installment options, commission percentages, ROI calculation, and compare with market rates.",
            promptTemplate: "Explain the price of the suggested product. Mention: price in BDT, commission percentage, potential earnings, and any installment option. Be transparent. Language: {{language}}. Tone: helpful, not pushy.",
            primaryModel: "claude-3.5-sonnet",
            fallbackModels: ["gpt-4o"],
            tier: 2,
            priority: 85,
            when: "intent === 'price_inquiry' || intent === 'purchase'",
          },
          {
            id: "benefit_highlighter",
            name: "Benefit Highlighter",
            nameBn: "সুবিধা তুলে ধরাকারী",
            department: "sales",
            team: "product_pitch",
            description: "Highlights top 3 benefits of the product",
            descriptionBn: "পণ্যের ৩টি প্রধান সুবিধা তুলে ধরে",
            expertise: "You know the top 3 benefits of every product: income potential, skill development, community support, flexibility, low investment, high return.",
            promptTemplate: "List exactly 3 benefits of this product for the customer. Make each benefit personal and relatable. Format as 3 bullet points in {{language}}. End with an open question.",
            primaryModel: "gpt-4o-mini",
            fallbackModels: ["claude-3-haiku"],
            tier: 3,
            priority: 75,
            when: "intent === 'product_inquiry' || intent === 'price_inquiry'",
          },
          {
            id: "comparison_builder",
            name: "Comparison Builder",
            nameBn: "তুলনা নির্মাতা",
            department: "sales",
            team: "product_pitch",
            description: "Compares our offer with competitors",
            descriptionBn: "আমাদের অফার প্রতিযোগীদের সাথে তুলনা করে",
            expertise: "You know competitor offerings in the Bangladesh MLM/e-commerce space and can objectively compare features, pricing, and benefits.",
            promptTemplate: "Compare our product with similar market offerings. Highlight our unique advantages: better commission structure, lower entry cost, Bangladeshi support, proven track record. Be honest, not aggressive. Language: {{language}}.",
            primaryModel: "claude-3.5-sonnet",
            fallbackModels: ["deepseek-chat"],
            tier: 2,
            priority: 65,
            when: "intent === 'product_inquiry'",
          },
          {
            id: "social_proof_injector",
            name: "Social Proof Injector",
            nameBn: "সামাজিক প্রমাণ প্রদানকারী",
            department: "sales",
            team: "product_pitch",
            description: "Shares success stories and testimonials",
            descriptionBn: "সফলতার গল্প ও প্রশংসাপত্র শেয়ার করে",
            expertise: "You share relevant success stories of Bangladeshi members who achieved results through our platform.",
            promptTemplate: "Share a relevant success story of a member who started similarly to this customer. Include: their background, what they did, what they achieved. Make it aspirational but realistic. Language: {{language}}.",
            primaryModel: "gpt-4o-mini",
            fallbackModels: ["claude-3-haiku"],
            tier: 3,
            priority: 55,
            when: "intent === 'product_inquiry' || intent === 'price_inquiry'",
          },
          {
            id: "urgency_creator",
            name: "Urgency Creator",
            nameBn: "জরুরিতা সৃষ্টিকারী",
            department: "sales",
            team: "product_pitch",
            description: "Creates gentle urgency with limited offers",
            descriptionBn: "সীমিত অফার দিয়ে মৃদু জরুরিতা তৈরি করে",
            expertise: "You create genuine urgency without being pushy: limited spots, seasonal bonuses, expiring discounts, exclusive access.",
            promptTemplate: "Gently mention any current limited offer, bonus, or deadline. Be honest — don't create fake urgency. If no offer exists, skip this. Language: {{language}}.",
            primaryModel: "gpt-4o-mini",
            fallbackModels: ["gemini-flash"],
            tier: 3,
            priority: 45,
            when: "intent === 'purchase' || intent === 'price_inquiry'",
          },
        ],
      },

      // ─── Team 1.3: Objection Handling ───
      {
        id: "objection_handling",
        name: "Objection Handling",
        nameBn: "আপত্তি ব্যবস্থাপনা",
        department: "sales",
        description: "Handle all 7 objection types with Yes-And + recovery",
        primaryModel: "gpt-4o",
        fallbackModels: ["claude-3.5-sonnet", "deepseek-chat"],
        agents: [
          {
            id: "price_objection_handler",
            name: "Price Objection Handler",
            nameBn: "দাম আপত্তি ব্যবস্থাপক",
            department: "sales",
            team: "objection_handling",
            description: "Handles 'price is too high' objections",
            descriptionBn: "'দাম বেশি' আপত্তি হ্যান্ডেল করে",
            expertise: "You handle price objections using Yes-And + Value Breakdown technique: acknowledge → break down value → show ROI → offer installment/plan.",
            promptTemplate: "Handle price objection. Steps: 1) Acknowledge ('আমি বুঝি') 2) Break down daily cost 3) Show earning potential 4) Offer installment if available. Be empathetic. Language: {{language}}.",
            primaryModel: "gpt-4o",
            fallbackModels: ["claude-3.5-sonnet"],
            tier: 1,
            priority: 95,
            when: "intent === 'price_inquiry'",
          },
          {
            id: "trust_objection_handler",
            name: "Trust Objection Handler",
            nameBn: "বিশ্বাস আপত্তি ব্যবস্থাপক",
            department: "sales",
            team: "objection_handling",
            description: "Handles 'is this a scam?' trust objections",
            descriptionBn: "'এটা কি প্রতারণা?' বিশ্বাস আপত্তি হ্যান্ডেল করে",
            expertise: "You handle trust objections: company registration proof, real office, existing member base, payment gateway (SSLCommerz), physical products, transparent commission system.",
            promptTemplate: "Handle trust objection. Steps: 1) Validate the concern ('ঠিকই ভেবেছেন') 2) Show proof: registered company, real office, SSLCommerz payment, existing members 3) Offer to connect with existing members 4) Start small (low ticket product). Language: {{language}}.",
            primaryModel: "claude-3.5-sonnet",
            fallbackModels: ["gpt-4o"],
            tier: 1,
            priority: 90,
            when: "intent === 'complaint' || intent === 'general'",
          },
          {
            id: "time_objection_handler",
            name: "Time Objection Handler",
            nameBn: "সময় আপত্তি ব্যবস্থাপক",
            department: "sales",
            team: "objection_handling",
            description: "Handles 'I don't have time' objections",
            descriptionBn: "'সময় নেই' আপত্তি হ্যান্ডেল করে",
            expertise: "You handle time objections using Micro-Commitment: start with 15 mins/day → show quick wins → build momentum.",
            promptTemplate: "Handle time objection. Steps: 1) Empathize ('জীবনে সবাই ব্যস্ত') 2) Micro-commitment: 'দিনে মাত্র ১৫ মিনিট' 3) Show quick-win example 4) Offer support system. Language: {{language}}.",
            primaryModel: "claude-3.5-sonnet",
            fallbackModels: ["gpt-4o-mini"],
            tier: 2,
            priority: 85,
            when: "intent === 'general'",
          },
          {
            id: "skill_objection_handler",
            name: "Skill Objection Handler",
            nameBn: "দক্ষতা আপত্তি ব্যবস্থাপক",
            department: "sales",
            team: "objection_handling",
            description: "Handles 'I can't do this' objections",
            descriptionBn: "'আমি পারব না' আপত্তি হ্যান্ডেল করে",
            expertise: "You handle skill objections: no experience needed → full training provided → support team → start with simple tasks.",
            promptTemplate: "Handle skill objection. Steps: 1) 'আমাদের অনেক সদস্যই প্রথমে একই কথা বলেছেন' 2) Training + support system 3) Start simple 4) Community help. Language: {{language}}.",
            primaryModel: "gpt-4o-mini",
            fallbackModels: ["claude-3-haiku"],
            tier: 3,
            priority: 80,
            when: "intent === 'general' || intent === 'registration'",
          },
          {
            id: "result_objection_handler",
            name: "Result Objection Handler",
            nameBn: "ফলাফল আপত্তি ব্যবস্থাপক",
            department: "sales",
            team: "objection_handling",
            description: "Handles 'will this actually work?' objections",
            descriptionBn: "'কাজ হবে তো?' আপত্তি হ্যান্ডেল করে",
            expertise: "You handle result objections: case studies, real data, performance metrics, member testimonials, money-back guarantee.",
            promptTemplate: "Handle result objection. Steps: 1) Show real data 2) Member case study 3) Start with small goal 4) Track progress. Be honest about effort required. Language: {{language}}.",
            primaryModel: "claude-3.5-sonnet",
            fallbackModels: ["gpt-4o"],
            tier: 2,
            priority: 75,
            when: "intent === 'product_inquiry' || intent === 'general'",
          },
          {
            id: "commitment_objection_handler",
            name: "Commitment Objection Handler",
            nameBn: "অঙ্গীকার আপত্তি ব্যবস্থাপক",
            department: "sales",
            team: "objection_handling",
            description: "Handles 'I'll think about it' objections",
            descriptionBn: "'ভাবছি' আপত্তি হ্যান্ডেল করে",
            expertise: "You handle commitment objections: low-risk trial → limited bonus → deadline → 'what's stopping you?' technique.",
            promptTemplate: "Handle commitment objection. Steps: 1) Acknowledge ('ভাবা ভালো') 2) Low-risk: trial/demo 3) Limited bonus if decide now 4) Gentle: 'কী আপত্তি থাকলে বলুন' 5) Suggest next step. Language: {{language}}.",
            primaryModel: "gpt-4o-mini",
            fallbackModels: ["claude-3-haiku"],
            tier: 3,
            priority: 70,
            when: "intent === 'purchase' || intent === 'registration'",
          },
          {
            id: "competitor_objection_handler",
            name: "Competitor Objection Handler",
            nameBn: "প্রতিযোগী আপত্তি ব্যবস্থাপক",
            department: "sales",
            team: "objection_handling",
            description: "Handles 'other company is better' objections",
            descriptionBn: "'অন্য কোম্পানি ভাল' আপত্তি হ্যান্ডেল করে",
            expertise: "You handle competitor objections without badmouthing: acknowledge competitor strength → show our unique advantage → focus on value, not price.",
            promptTemplate: "Handle competitor objection. 1) Respect their choice 2) Acknowledge competitor's strength 3) Show OUR unique advantage 4) Let the facts speak. Never badmouth competitors. Language: {{language}}.",
            primaryModel: "claude-3.5-sonnet",
            fallbackModels: ["deepseek-chat"],
            tier: 2,
            priority: 65,
            when: "intent === 'product_inquiry'",
          },
          {
            id: "no_recovery_agent",
            name: "No Recovery Agent",
            nameBn: "না পুনরুদ্ধার এজেন্ট",
            department: "sales",
            team: "objection_handling",
            description: "3-level recovery when customer says no",
            descriptionBn: "গ্রাহক 'না' বললে ৩-লেভেল পুনরুদ্ধার",
            expertise: "You have 3 levels of recovery: SOFT (understand, leave door open), FIRM (address specific concern, offer alternative), PERMANENT (polite exit, future follow-up).",
            promptTemplate: "Customer said no. Apply recovery level based on firmness: SOFT → 'বুঝলাম, পরে প্রয়োজন হলে জানাবেন' FIRM → 'শুধু一个问题, কী কারণে?' PERMANENT → 'বুঝলাম, ধন্যবাদ। ভবিষ্যতে খোজ নেব।' Output only the recovery response. Language: {{language}}.",
            primaryModel: "claude-3.5-sonnet",
            fallbackModels: ["gpt-4o-mini"],
            tier: 2,
            priority: 95,
            when: "intent === 'purchase' || intent === 'registration'",
          },
        ],
      },

      // ─── Team 1.4: Closing & Conversion ───
      {
        id: "closing_conversion",
        name: "Closing & Conversion",
        nameBn: "ক্লোজিং ও কনভার্সন",
        department: "sales",
        description: "Close deals with trials, discounts, installments, referrals",
        primaryModel: "claude-3.5-sonnet",
        fallbackModels: ["gpt-4o", "deepseek-chat"],
        agents: [
          {
            id: "trial_closer",
            name: "Trial Closer",
            nameBn: "ট্রায়াল ক্লোজার",
            department: "sales",
            team: "closing_conversion",
            description: "Offers free trial/demo to hesitant customers",
            descriptionBn: "দ্বিধাগ্রস্ত গ্রাহকদের ফ্রি ট্রায়াল/ডেমো অফার",
            expertise: "You offer low-commitment trials: free consultation, demo access, trial period, sample product, or workshop invitation.",
            promptTemplate: "Offer a low-risk trial: free consultation call, demo access, or trial period. Make it easy to say YES. 'কোনো ঝুঁকি নেই, আপনি দেখুন, পছন্দ হলে করবেন।' Language: {{language}}.",
            primaryModel: "gpt-4o-mini",
            fallbackModels: ["claude-3-haiku"],
            tier: 3,
            priority: 90,
            when: "intent === 'purchase' || intent === 'registration'",
          },
          {
            id: "discount_closer",
            name: "Discount Closer",
            nameBn: "ডিসকাউন্ট ক্লোজার",
            department: "sales",
            team: "closing_conversion",
            description: "Offers discounts and bonuses",
            descriptionBn: "ছাড় ও বোনাস অফার করে",
            expertise: "You offer strategic discounts: time-limited, bundle deals, early bird, referral discount, seasonal offers.",
            promptTemplate: "Offer a relevant discount or bonus. 'আজই যোগ দিলে বিশেষ ছাড় + বোনাস প্যাকেজ' Mention the real value. Create genuine urgency. Language: {{language}}.",
            primaryModel: "gpt-4o-mini",
            fallbackModels: ["claude-3-haiku"],
            tier: 3,
            priority: 85,
            when: "intent === 'price_inquiry' || intent === 'purchase'",
          },
          {
            id: "installment_closer",
            name: "Installment Closer",
            nameBn: "কিস্তি ক্লোজার",
            department: "sales",
            team: "closing_conversion",
            description: "Offers installment payment options",
            descriptionBn: "কিস্তি পেমেন্ট অপশন অফার করে",
            expertise: "You explain installment plans: monthly payment options, no-interest plans, flexible terms suitable for Bangladeshi customers.",
            promptTemplate: "Offer installment plan. Break down total into monthly payments. 'মাসে মাত্র X টাকা দিয়েই শুরু করতে পারেন' Show how affordable it is. Language: {{language}}.",
            primaryModel: "gpt-4o-mini",
            fallbackModels: ["gemini-flash"],
            tier: 3,
            priority: 80,
            when: "intent === 'price_inquiry' || intent === 'purchase'",
          },
          {
            id: "referral_closer",
            name: "Referral Closer",
            nameBn: "রেফারেল ক্লোজার",
            department: "sales",
            team: "closing_conversion",
            description: "Uses referral/team-building angle",
            descriptionBn: "রেফারেল/টিম বিল্ডিং অ্যাঙ্গেল ব্যবহার করে",
            expertise: "You use the referral opportunity: bring friends/family → earn more commissions → build a team → passive income.",
            promptTemplate: "Mention the referral/team benefit. 'শুধু নিজে যোগ দিলেই নয়, বন্ধু-পরিজনকে নিয়ে আসলে আরও আয়' Explain how team building multiplies earnings. Language: {{language}}.",
            primaryModel: "gpt-4o-mini",
            fallbackModels: ["claude-3-haiku"],
            tier: 3,
            priority: 70,
            when: "intent === 'registration' || intent === 'purchase'",
          },
          {
            id: "payment_link_sender",
            name: "Payment Link Sender",
            nameBn: "পেমেন্ট লিংক প্রেরক",
            department: "sales",
            team: "closing_conversion",
            description: "Generates and sends payment link",
            descriptionBn: "পেমেন্ট লিংক তৈরি ও পাঠায়",
            expertise: "You generate SSLCommerz payment links and guide customers through the payment process step by step.",
            promptTemplate: "Guide customer to payment. Provide clear steps: 1) Click link 2) Select payment method (bKash/Nagad/card) 3) Complete payment 4) Confirmation. Be patient and helpful. Language: {{language}}.",
            primaryModel: "gpt-4o-mini",
            fallbackModels: ["claude-3-haiku"],
            tier: 3,
            priority: 95,
            when: "intent === 'purchase'",
          },
          {
            id: "confirmation_sender",
            name: "Confirmation Sender",
            nameBn: "নিশ্চিতকরণ প্রেরক",
            department: "sales",
            team: "closing_conversion",
            description: "Sends order confirmation and thank you",
            descriptionBn: "অর্ডার কনফার্মেশন ও থ্যাংক ইউ পাঠায়",
            expertise: "You send warm confirmations with next steps, making customers feel valued and excited about their decision.",
            promptTemplate: "Send a warm confirmation message. Thank them, confirm what they purchased, explain next steps, and express excitement for their journey. Language: {{language}}.",
            primaryModel: "gpt-4o-mini",
            fallbackModels: ["gemini-flash"],
            tier: 4,
            priority: 100,
            when: "intent === 'purchase'",
          },
        ],
      },

      // ─── Team 1.5: Follow-up & Retention ───
      {
        id: "followup_retention",
        name: "Follow-up & Retention",
        nameBn: "ফলো-আপ ও ধরে রাখা",
        department: "sales",
        description: "Schedule follow-ups, re-engage, cross-sell, upsell",
        primaryModel: "gpt-4o-mini",
        fallbackModels: ["claude-3-haiku", "gemini-flash"],
        agents: [
          {
            id: "followup_scheduler",
            name: "Follow-up Scheduler",
            nameBn: "ফলো-আপ শিডিউলার",
            department: "sales",
            team: "followup_retention",
            description: "Determines optimal follow-up timing",
            descriptionBn: "সর্বোত্তম ফলো-আপ সময় নির্ধারণ করে",
            expertise: "You determine follow-up timing based on customer behavior: hot → 1hr, warm → 24hr, cold → 72hr, no response → 48hr.",
            promptTemplate: "Determine follow-up timing: if hot lead → '1hour', if interested+warm → '24hours', if cold → '72hours', if no reply → '48hours'. Return timing + brief reason.",
            primaryModel: "gpt-4o-mini",
            fallbackModels: ["claude-3-haiku"],
            tier: 3,
            priority: 75,
            when: "true",
          },
          {
            id: "followup_content_gen",
            name: "Follow-up Content Generator",
            nameBn: "ফলো-আপ কন্টেন্ট জেনারেটর",
            department: "sales",
            team: "followup_retention",
            description: "Generates follow-up message content",
            descriptionBn: "ফলো-আপ মেসেজ কন্টেন্ট তৈরি করে",
            expertise: "You create personalized follow-up messages: value-add (tips, updates), social proof (success stories), gentle reminders, offers.",
            promptTemplate: "Create a follow-up message for this lead. Make it personal, add value (tip/update/story), and end with a low-pressure question. Previous context: {{context}}. Language: {{language}}.",
            primaryModel: "claude-3.5-sonnet",
            fallbackModels: ["gpt-4o-mini"],
            tier: 2,
            priority: 70,
            when: "true",
          },
          {
            id: "re_engagement_trigger",
            name: "Re-engagement Trigger",
            nameBn: "পুনরায় সম্পৃক্তকরণ",
            department: "sales",
            team: "followup_retention",
            description: "Re-engages inactive leads",
            descriptionBn: "নিষ্ক্রিয় লিড পুনরায় সক্রিয় করে",
            expertise: "You re-engage inactive leads with: new offers, success stories, asking about their situation, exclusive invitations.",
            promptTemplate: "Re-engage an inactive lead. Use one of: 1) New offer 2) Success story 3) 'How have you been?' 4) Event invitation. Don't sound desperate. Language: {{language}}.",
            primaryModel: "gpt-4o-mini",
            fallbackModels: ["gemini-flash"],
            tier: 3,
            priority: 60,
            when: "true",
          },
          {
            id: "cross_sell_offer",
            name: "Cross-sell Offer",
            nameBn: "ক্রস-সেল অফার",
            department: "sales",
            team: "followup_retention",
            description: "Suggests related products to existing customers",
            descriptionBn: "বিদ্যমান গ্রাহকদের সম্পর্কিত পণ্য সুপারিশ",
            expertise: "You suggest complementary products based on what was already purchased: product + training, membership + upgrade, course + community access.",
            promptTemplate: "Suggest a related product. Mention: 'যেহেতু আপনি X নিয়েছেন, Y আপনার জন্য পারফেক্ট হবে' Explain how they complement each other. Language: {{language}}.",
            primaryModel: "gpt-4o-mini",
            fallbackModels: ["claude-3-haiku"],
            tier: 3,
            priority: 50,
            when: "intent === 'purchase'",
          },
          {
            id: "upsell_offer",
            name: "Upsell Offer",
            nameBn: "আপসেল অফার",
            department: "sales",
            team: "followup_retention",
            description: "Offers premium/better version",
            descriptionBn: "প্রিমিয়াম/উন্নত ভার্সন অফার",
            expertise: "You offer premium upgrades: basic→pro, individual→team, monthly→yearly (discount), limited edition packages.",
            promptTemplate: "Offer a premium upgrade. Show the additional value: more features, higher commissions, priority support, exclusive access. 'আপনি ইতিমধ্যেই ভাল করছেন, প্রিমিয়াম ভার্সনে আরও ভাল করবেন।' Language: {{language}}.",
            primaryModel: "claude-3.5-sonnet",
            fallbackModels: ["gpt-4o-mini"],
            tier: 2,
            priority: 45,
            when: "intent === 'purchase'",
          },
          {
            id: "loyalty_rewarder",
            name: "Loyalty Rewarder",
            nameBn: "আনুগত্য পুরস্কারদাতা",
            department: "sales",
            team: "followup_retention",
            description: "Rewards loyal customers with special bonuses",
            descriptionBn: "অনুগত গ্রাহকদের বিশেষ বোনাস দেয়",
            expertise: "You identify and reward loyal customers: repeat purchases → special discount, referrals → bonus commission, long-term → exclusive status.",
            promptTemplate: "Create a loyalty reward message for a repeat customer. Thank them for their continued trust and offer an exclusive reward (special discount, bonus, or status). Language: {{language}}.",
            primaryModel: "gpt-4o-mini",
            fallbackModels: ["claude-3-haiku"],
            tier: 3,
            priority: 40,
            when: "intent === 'purchase'",
          },
        ],
      },

      // ─── Team 1.6: Campaign Management ───
      {
        id: "campaign_management",
        name: "Campaign Management",
        nameBn: "ক্যাম্পেইন ব্যবস্থাপনা",
        department: "sales",
        description: "Plan, craft, send, and analyze campaigns",
        primaryModel: "gpt-4o-mini",
        fallbackModels: ["gemini-flash", "claude-3-haiku"],
        agents: [
          {
            id: "campaign_planner",
            name: "Campaign Planner",
            nameBn: "ক্যাম্পেইন পরিকল্পনাকারী",
            department: "sales",
            team: "campaign_management",
            description: "Plans campaign goals and target audience",
            descriptionBn: "ক্যাম্পেইনের লক্ষ্য ও টার্গেট নির্ধারণ করে",
            expertise: "You plan campaigns: define goal (awareness/sales/recruitment), target segment (student/homemaker/job holder), message strategy, timeline.",
            promptTemplate: "Plan a campaign: define goal, target audience (age/gender/sector), key message, channel (WhatsApp/SMS/Email), timeline. Consider Bengali audience preferences. Output structured plan.",
            primaryModel: "claude-3.5-sonnet",
            fallbackModels: ["gpt-4o-mini"],
            tier: 2,
            priority: 80,
            when: "true",
          },
          {
            id: "message_crafter",
            name: "Message Crafter",
            nameBn: "মেসেজ কারিগর",
            department: "sales",
            team: "campaign_management",
            description: "Crafts campaign messages (A/B variants)",
            descriptionBn: "ক্যাম্পেইন মেসেজ তৈরি করে (A/B ভেরিয়েন্ট)",
            expertise: "You create compelling campaign messages: attention-grabbing opening, clear value proposition, strong CTA, personalization with {name}.",
            promptTemplate: "Create a campaign message. Include: attention hook, value proposition, social proof, urgency, clear CTA. Make it conversational Bengali. Create 2 variants (A and B) for testing.",
            primaryModel: "claude-3.5-sonnet",
            fallbackModels: ["deepseek-chat"],
            tier: 2,
            priority: 90,
            when: "true",
          },
          {
            id: "audience_selector",
            name: "Audience Selector",
            nameBn: "অডিয়েন্স সিলেক্টর",
            department: "sales",
            team: "campaign_management",
            description: "Selects the right contact list for campaigns",
            descriptionBn: "ক্যাম্পেইনের জন্য সঠিক কন্ট্যাক্ট লিস্ট সিলেক্ট করে",
            expertise: "You segment audiences: by sector (student/business/homemaker), by status (new/contacted/converted), by priority score, by location.",
            promptTemplate: "Select audience for this campaign based on goal. Segment by: sector, status, priority, age. Return filter criteria (SQL-style WHERE clause).",
            primaryModel: "gpt-4o-mini",
            fallbackModels: ["gemini-flash"],
            tier: 3,
            priority: 70,
            when: "true",
          },
          {
            id: "send_time_optimizer",
            name: "Send Time Optimizer",
            nameBn: "প্রেরণ সময় অপটিমাইজার",
            department: "sales",
            team: "campaign_management",
            description: "Optimizes when to send for max response",
            descriptionBn: "সর্বোচ্চ রেসপন্সের জন্য পাঠানোর সময় অপটিমাইজ করে",
            expertise: "You optimize send times based on Bangladeshi user behavior: morning (8-10am for homemakers), afternoon (2-4pm for job holders), evening (8-10pm for students).",
            promptTemplate: "Suggest best send time for this audience segment. Consider their daily routine in Bangladesh context. Return time + timezone (+6) + reasoning.",
            primaryModel: "gpt-4o-mini",
            fallbackModels: ["gemini-flash"],
            tier: 3,
            priority: 60,
            when: "true",
          },
          {
            id: "campaign_analyzer",
            name: "Campaign Analyzer",
            nameBn: "ক্যাম্পেইন বিশ্লেষক",
            department: "sales",
            team: "campaign_management",
            description: "Analyzes campaign performance",
            descriptionBn: "ক্যাম্পেইন পারফরম্যান্স বিশ্লেষণ করে",
            expertise: "You analyze campaign metrics: sent count, delivery rate, reply rate, conversion rate, ROI, and suggest improvements.",
            promptTemplate: "Analyze this campaign's performance: sent={{sent}}, delivered={{delivered}}, replied={{replied}}, converted={{converted}}. Calculate rates, identify issues, suggest 3 improvements. Language: {{language}}.",
            primaryModel: "gpt-4o-mini",
            fallbackModels: ["claude-3-haiku"],
            tier: 3,
            priority: 50,
            when: "true",
          },
          {
            id: "ab_tester",
            name: "A/B Tester",
            nameBn: "A/B টেস্টার",
            department: "sales",
            team: "campaign_management",
            description: "Runs A/B tests and selects winner",
            descriptionBn: "A/B টেস্ট চালিয়ে বিজয়ী নির্বাচন করে",
            expertise: "You design A/B tests: single variable change, sufficient sample size, statistical significance, winner selection logic.",
            promptTemplate: "Design an A/B test: variant A={{msgA}}, variant B={{msgB}}. Test variable, sample size per variant, duration, success metric. After test: select winner with reasoning.",
            primaryModel: "gpt-4o-mini",
            fallbackModels: ["gemini-flash"],
            tier: 3,
            priority: 40,
            when: "true",
          },
        ],
      },
    ],
  },

  // ════════════════════════════════════════════
  // OTHER DEPARTMENTS (Phase 2+)
  // Placeholder definitions for routing
  // ════════════════════════════════════════════
  member_success: {
    id: "member_success",
    name: "Member Success",
    nameBn: "মেম্বার সাফল্য",
    icon: "👥",
    description: "Recruitment, training, performance, motivation (Phase 2)",
    primaryModel: "claude-3.5-sonnet",
    fallbackModels: ["gpt-4o", "deepseek-chat"],
    teams: [],
  },
  customer_experience: {
    id: "customer_experience",
    name: "Customer Experience",
    nameBn: "গ্রাহক অভিজ্ঞতা",
    icon: "🤝",
    description: "Support, feedback, premium service (Phase 2)",
    primaryModel: "claude-3.5-sonnet",
    fallbackModels: ["gpt-4o", "deepseek-chat"],
    teams: [],
  },
  operations: {
    id: "operations",
    name: "Operations",
    nameBn: "অপারেশনস",
    icon: "⚙️",
    description: "Orders, payments, withdrawals (Phase 3)",
    primaryModel: "gpt-4o",
    fallbackModels: ["claude-3.5-sonnet", "deepseek-chat"],
    teams: [],
  },
  business_intelligence: {
    id: "business_intelligence",
    name: "Business Intelligence",
    nameBn: "বুদ্ধিমত্তা ও গবেষণা",
    icon: "📊",
    description: "Market research, analytics, knowledge (Phase 4)",
    primaryModel: "claude-3.5-sonnet",
    fallbackModels: ["gpt-4o", "deepseek-chat"],
    teams: [],
  },
  psychology: {
    id: "psychology",
    name: "Psychology & Optimization",
    nameBn: "মনোবিজ্ঞান ও উন্নয়ন",
    icon: "🧠",
    description: "Personality, persuasion, EQ, behavior (Phase 5)",
    primaryModel: "claude-3.5-sonnet",
    fallbackModels: ["gpt-4o", "deepseek-chat"],
    teams: [],
  },
  platform_admin: {
    id: "platform_admin",
    name: "Platform Administration",
    nameBn: "প্ল্যাটফর্ম প্রশাসন",
    icon: "🛠️",
    description: "Content, config, security, health (Phase 3)",
    primaryModel: "gpt-4o-mini",
    fallbackModels: ["claude-3-haiku", "gemini-flash"],
    teams: [],
  },
};

export function getDepartment(id: DepartmentId): DepartmentDef {
  return DEPARTMENTS[id];
}

export function getAllDepartments(): DepartmentDef[] {
  return Object.values(DEPARTMENTS);
}

export function findAgent(agentId: string): { agent: import("./types").AgentDef; department: DepartmentId; team: string } | null {
  for (const dept of Object.values(DEPARTMENTS)) {
    for (const team of dept.teams) {
      const agent = team.agents.find((a) => a.id === agentId);
      if (agent) return { agent, department: dept.id, team: team.id };
    }
  }
  return null;
}

export function getAgentsByTeam(teamId: string): import("./types").AgentDef[] {
  for (const dept of Object.values(DEPARTMENTS)) {
    for (const team of dept.teams) {
      if (team.id === teamId) return team.agents;
    }
  }
  return [];
}

export function getAgentsByDepartment(deptId: DepartmentId): import("./types").AgentDef[] {
  const dept = DEPARTMENTS[deptId];
  if (!dept) return [];
  return dept.teams.flatMap((t) => t.agents);
}
